# Generated by Django 5.1.1 on 2024-11-08 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='نام گروه')),
            ],
            options={
                'verbose_name': 'گروه محصولات',
                'verbose_name_plural': 'گروه های محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('product_code', models.SlugField(blank=True, unique=True, verbose_name='کد محصول')),
                ('name', models.CharField(max_length=256, verbose_name='نام محصول')),
                ('colleague_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت هر کیلو گرم برای همکار(ریال)')),
                ('buy_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت هر کیلو گرم برای فروش (ریال)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='system.groupproduct', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات سیستم',
                'ordering': ['id'],
            },
        ),
    ]
