# Generated by Django 5.1.1 on 2024-10-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsystem',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='system.groupproduct', verbose_name='گروه'),
            preserve_default=False,
        ),
    ]
