# Generated by Django 5.1.1 on 2024-10-19 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsystem',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات سیستم'},
        ),
    ]
