# Generated by Django 5.1 on 2024-11-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsystem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
