# Generated by Django 5.1 on 2024-11-04 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_productsystem_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsystem',
            options={'ordering': ['created'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات سیستم'},
        ),
    ]
