# Generated by Django 5.1.1 on 2024-10-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_productsystem_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsystem',
            name='buy_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت هر کیلو گرم برای فروش (ریال)'),
        ),
        migrations.AlterField(
            model_name='productsystem',
            name='colleague_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت هر کیلو گرم برای همکار(ریال)'),
        ),
    ]
