# Generated by Django 5.1.1 on 2024-11-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_productsystem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsystem',
            options={'ordering': ['id'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات سیستم'},
        ),
        migrations.RemoveField(
            model_name='productsystem',
            name='created',
        ),
    ]
