services : 
  redis :
    image : redis 
    ports : 
      - 6379:6379
    restart : always
  db : 
    image : postgres
    restart : always
    ports : 
        - "5432:5432"
    environment : 
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=kimia_db 
      - POSTGRES_USER=kimia_user
      - POSTGRES_PASSWORD=kimia_password
    volumes : 
      - pgdata:/var/lib/postgresql/data
    
  pgadmin : 
    image : dpage/pgadmin4
    restart : always
    ports : 
      - "8888:80"
    environment : 
      PGADMIN_DEFAULT_EMAIL : kimia@gmail.com
      PGADMIN_DEFAULT_PASSWORD : password
    volumes : 
      - pgadmin-data:/var/lib/pgadmin
  
  celery : 
    build :
      context : ./
      dockerfile : ./Dockerfile
    restart : always
    command : celery -A core worker --loglevel=INFO
    environment : 
      - DEBUG=True
      - DATABASE_NAME=kimia_db
      - DATABASE_USER=kimia_user
      - DATABASE_PASSWORD=kimia_password
      - DATABASE_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/
      - CELERY_RESULT_BACKEND=redis://redis:6379/
    volumes :
      - .:/app
    depends_on : 
      - db
      - redis
  django : 
    build : 
      context : ./
      dockerfile : ./Dockerfile
    ports : 
      - "8000:8000"
    environment : 
      - DEBUG=True
      - DATABASE_NAME=kimia_db
      - DATABASE_USER=kimia_user
      - DATABASE_PASSWORD=kimia_password
      - DATABASE_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/
      - CELERY_RESULT_BACKEND=redis://redis:6379/
    depends_on : 
      - db
    volumes :
      - .:/app
    command : ["sh","start.sh"]
volumes :
  pgdata:
  pgadmin-data: