services : 

  db : 
    image : postgres
    restart : always
    ports : 
        - "5432:5432"
    environment : 
      - POSTGRES_HOST_AUTH_METHOD=trust
#    volumes:
#      - pgdata:/var/lib/postgresql/data
    
  pgadmin : 
    image : dpage/pgadmin4
    restart : always
    ports : 
      - "8888:80"
    environment : 
      PGADMIN_DEFAULT_EMAIL : example@gmail.com
      PGADMIN_DEFAULT_PASSWORD : password
  
  django : 
    build : 
      context : ./
      dockerfile : ./Dockerfile
    ports : 
      - "8000:8000"
    environment : 
      - DEBUG=True
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - ALLOWED_HOSTS=localhost,ksparseh.com,www.kspareseh.com,cms.ksparseh.com,www.cms.ksparseh.com,127.0.0.1
      - ALLOWED_ORIGINS=http://localhost,https://ksparseh.com,https://www.kspareseh.com,https://cms.ksparseh.com,https://www.cms.ksparseh.com
    depends_on : 
      - db
    volumes :
      - .:/app
    command : ["sh","start.sh"]
volumes :
  pgdata: