# Generated by Django 5.1.1 on 2024-10-19 07:12

import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='نام راننده')),
                ('license_plate', models.SlugField(max_length=8, unique=True, verbose_name='پلاک راننده')),
                ('car', models.CharField(max_length=256, verbose_name='ماشین راننده')),
                ('phone', models.SlugField(max_length=11, unique=True, verbose_name='شماره راننده')),
                ('national_id', models.PositiveBigIntegerField(unique=True, verbose_name='شناسه راننده')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'راننده',
                'verbose_name_plural': 'راننده ها',
            },
        ),
    ]
