# Generated by Django 5.1.1 on 2024-10-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='national_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='شناسه راننده'),
        ),
    ]
