# Generated by Django 5.1.1 on 2024-11-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_plate',
            field=models.CharField(max_length=12, verbose_name='پلاک راننده'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=256, verbose_name='نام راننده'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='national_id',
            field=models.PositiveBigIntegerField(verbose_name='شناسه راننده'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.SlugField(max_length=11, verbose_name='شماره راننده'),
        ),
    ]
