# Generated by Django 5.1.1 on 2024-10-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_plate',
            field=models.CharField(max_length=12, unique=True, verbose_name='پلاک راننده'),
        ),
    ]
