# Generated by Django 5.1 on 2024-10-31 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_alter_driver_license_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAddPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان ')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
            ],
            options={
                'verbose_name': 'صفحه افزودن راننده',
                'verbose_name_plural': 'صفحه افزودن راننده',
            },
        ),
    ]
