# Generated by Django 5.1.1 on 2024-09-19 06:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='نام راننده')),
                ('license_plate', models.SlugField(max_length=13, unique=True, verbose_name='پلاک راننده')),
                ('phone', models.SlugField(max_length=11, unique=True, verbose_name='شماره راننده')),
                ('national_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='کد ملی')),
            ],
            options={
                'verbose_name': 'راننده',
                'verbose_name_plural': 'راننده ها',
            },
        ),
    ]
