# Generated by Django 5.1.1 on 2024-09-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car',
            field=models.CharField(default=None, max_length=256, verbose_name='ماشین راننده'),
            preserve_default=False,
        ),
    ]
