# Generated by Django 5.1.1 on 2024-09-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profuser', '0002_driver_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='national_id',
            field=models.PositiveBigIntegerField(default=None, unique=True, verbose_name='کد ملی'),
            preserve_default=False,
        ),
    ]
