# Generated by Django 5.1.1 on 2024-11-08 12:26

import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('description', models.TextField(verbose_name='توضیحات دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول',
                'verbose_name_plural': 'دسته بندی های محصول',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='نام و نام خانوادگی')),
                ('is_from_admin', models.BooleanField(default=False, verbose_name='از طرف ادمین')),
                ('reply_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='رپلای به چه کسی')),
                ('description', models.TextField(verbose_name='پیام کاربر')),
                ('is_valid', models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت های محصولات',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FeatureProduct',
            fields=[
                ('key', models.CharField(max_length=256, verbose_name='کلید')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=256, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'مشخصات فیزیکی و شیمیای محصول',
                'verbose_name_plural': 'مشخصات فیزیکی و شیمیای محصول',
            },
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='product/images/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='product/video/', verbose_name='ویدیو')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/images/', verbose_name='تصویر شاخص')),
                ('code', models.SlugField(max_length=20, verbose_name='کد محصول')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='عنوان محصول')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات کوتاه')),
                ('type', models.CharField(choices=[('pasty', 'خمیری'), ('fluid', 'مایع'), ('powdery', 'پودری')], default='fluid', max_length=10, verbose_name='نوع محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('maintain_description', models.TextField(blank=True, null=True, verbose_name='روند نگهداری محصول')),
                ('consumtion_order', models.TextField(blank=True, null=True, verbose_name='روش مصرف')),
                ('packing_description', models.TextField(blank=True, null=True, verbose_name='بسته بندی محصول')),
                ('catalog_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='آدرس کاتالوگ')),
                ('catalog_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='فایل کاتالوگ')),
                ('created', django_jalali.db.models.jDateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='نام استاندارد')),
                ('image', models.ImageField(upload_to='product/standard/image/', verbose_name='تصویر استاندارد')),
                ('text', models.TextField(blank=True, null=True, verbose_name='توضیحات استاندارد')),
            ],
            options={
                'verbose_name': 'استاندارد',
                'verbose_name_plural': 'استاندارد ها',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UsageProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=256, verbose_name='کاربرد')),
            ],
            options={
                'verbose_name': 'کاربرد محصول',
                'verbose_name_plural': 'کاربرد های محصول',
            },
        ),
        migrations.CreateModel(
            name='ViolationComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('topic', models.CharField(max_length=256, verbose_name='موضوع')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'گزارش تخلف کامنت',
                'verbose_name_plural': 'گزارشات تخلف کامنت ها',
            },
        ),
    ]
