# Generated by Django 5.1.1 on 2024-09-18 08:39

import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('icon', models.ImageField(upload_to='product/category/icon/', verbose_name='آیکون')),
                ('description', models.TextField(verbose_name='توضیحات دسته بندی')),
                ('show_in_home', models.BooleanField(default=False, verbose_name='نمایش در صفحه هوم')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول',
                'verbose_name_plural': 'دسته بندی های محصول',
            },
        ),
        migrations.CreateModel(
            name='FeatureProduct',
            fields=[
                ('key', models.CharField(max_length=256, verbose_name='کلید')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=256, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'مشخصات فیزیکی و شیمیای محصول',
                'verbose_name_plural': 'مشخصات فیزیکی و شیمیای محصول',
            },
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='product/images/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='نام استاندارد')),
                ('image', models.ImageField(upload_to='product/standard/image/', verbose_name='تصویر استاندارد')),
                ('text', models.TextField(verbose_name='توضیحات استاندارد')),
            ],
            options={
                'verbose_name': 'استاندارد',
                'verbose_name_plural': 'استاندارد ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='نام برچسب')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='UsageProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=256, verbose_name='کاربرد')),
            ],
            options={
                'verbose_name': 'کاربرد محصول',
                'verbose_name_plural': 'کاربرد های محصول',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_valid', models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='product.comment', verbose_name='پاسخ به')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت های محصولات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('video', models.FileField(upload_to='product/video/', verbose_name='ویدیو')),
                ('code', models.SlugField(max_length=20, verbose_name='کد انباری محصول')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='عنوان محصول')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('type', models.CharField(choices=[('pasty', 'خمیری'), ('fluid', 'مایع'), ('powdery', 'پودری')], default='fluid', max_length=10, verbose_name='نوع محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('catalog_url', models.URLField(blank=True, null=True, verbose_name='آدرس کاتالوگ')),
                ('maintain_description', models.TextField(blank=True, null=True, verbose_name='روش نگهداری محصول')),
                ('consumtion_order', models.TextField(blank=True, null=True, verbose_name='روش مصرف')),
                ('immunity_description', models.TextField(blank=True, null=True, verbose_name='ایمنی محصول')),
                ('packing_description', models.TextField(blank=True, null=True, verbose_name='دسته بندی محصول')),
                ('created', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
