# Generated by Django 5.1.1 on 2024-09-24 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.ManyToManyField(to='user.ip'),
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='featureproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='count',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='product.product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='standard',
            field=models.ManyToManyField(blank=True, to='product.standard', verbose_name='استاندارد ها'),
        ),
        migrations.AddField(
            model_name='usageproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='product.product', verbose_name='محصول'),
        ),
    ]
