# Generated by Django 5.1.1 on 2024-09-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AddField(
            model_name='product',
            name='standard',
            field=models.ManyToManyField(to='product.standard', verbose_name='استاندارد ها'),
        ),
    ]
