# Generated by Django 5.1.1 on 2024-09-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_product_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureproduct',
            name='value',
            field=models.CharField(max_length=256, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='usageproduct',
            name='value',
            field=models.CharField(max_length=256, verbose_name='کاربرد'),
        ),
    ]
