# Generated by Django 5.1.1 on 2024-10-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_products_count'),
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Count',
        ),
    ]
