# Generated by Django 5.1.1 on 2024-10-10 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('topic', models.CharField(max_length=256, verbose_name='موضوع')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='product.comment', verbose_name='کامنت')),
            ],
            options={
                'verbose_name': 'گزارش تخلف کامنت',
                'verbose_name_plural': 'گزارشات تخلف کامنت ها',
            },
        ),
    ]
