# Generated by Django 5.1 on 2024-11-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='phone',
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='merajpiri@gmail.com', max_length=254, verbose_name='ایمیل'),
            preserve_default=False,
        ),
    ]
