# Generated by Django 5.1.1 on 2024-09-19 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('count', models.CharField(max_length=256, verbose_name='مقدار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='product.product')),
            ],
            options={
                'verbose_name': 'مقدار محصول',
                'verbose_name_plural': 'مقادیر محصول',
            },
        ),
    ]
