# Generated by Django 5.1.1 on 2024-09-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
