# Generated by Django 5.1.1 on 2024-11-10 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureproduct',
            options={'ordering': ['created'], 'verbose_name': 'مشخصات فیزیکی و شیمیای محصول', 'verbose_name_plural': 'مشخصات فیزیکی و شیمیای محصول'},
        ),
        migrations.AddField(
            model_name='featureproduct',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
