# Generated by Django 5.1.1 on 2024-10-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_main_image_alter_product_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_image',
            new_name='image',
        ),
    ]
