# Generated by Django 5.1.1 on 2024-11-10 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_featureproduct_options_featureproduct_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usageproduct',
            options={'ordering': ['created'], 'verbose_name': 'کاربرد محصول', 'verbose_name_plural': 'کاربرد های محصول'},
        ),
        migrations.AddField(
            model_name='usageproduct',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
