# Generated by Django 5.1.1 on 2024-10-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_comment_disliked_by_comment_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='immunity_description',
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.SlugField(max_length=20, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='maintain_description',
            field=models.TextField(blank=True, null=True, verbose_name='روند نگهداری محصول'),
        ),
    ]
