# Generated by Django 5.1.1 on 2024-11-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_usageproduct_options_usageproduct_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureproduct',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usageproduct',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
