# Generated by Django 5.1.1 on 2024-10-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_main_image_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_from_admin',
            field=models.BooleanField(default=False, verbose_name='از طرف ادمین'),
        ),
    ]
