# Generated by Django 5.1.1 on 2024-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_liked_product_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='ایکون'),
        ),
    ]
