# Generated by Django 5.1.1 on 2024-10-12 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_comment_description_alter_comment_reply_to'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مقدار محصول در انبار'),
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stock.productgroup'),
        ),
    ]
