# Generated by Django 5.1 on 2024-11-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_comment_reply_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalog_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='فایل کاتالوگ'),
        ),
    ]
