# Generated by Django 5.1.1 on 2024-11-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_featureproduct_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usageproduct',
            name='value',
            field=models.TextField(verbose_name='کاربرد'),
        ),
    ]
