# Generated by Django 5.1.1 on 2024-10-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_count_price_product_count_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packing_description',
            field=models.TextField(blank=True, null=True, verbose_name='بسته بندی محصول'),
        ),
    ]
