# Generated by Django 5.1.1 on 2024-10-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_packing_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='count',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
    ]
