# Generated by Django 5.1 on 2024-11-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_catalog_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalog_url',
            field=models.SlugField(blank=True, null=True, verbose_name='آدرس کاتالوگ'),
        ),
    ]
