# Generated by Django 5.1.1 on 2024-10-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_count_price_remove_product_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='d',
            field=models.BooleanField(default=False),
        ),
    ]
