# Generated by Django 5.1 on 2024-11-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_catalog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalog_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='آدرس کاتالوگ'),
        ),
    ]
