# Generated by Django 5.1.1 on 2024-10-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='d',
        ),
    ]
