# Generated by Django 5.1.1 on 2024-11-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_comment_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات استاندارد'),
        ),
    ]
