# Generated by Django 5.1.1 on 2024-11-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_standard_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standard',
            options={'ordering': ['id'], 'verbose_name': 'استاندارد', 'verbose_name_plural': 'استاندارد ها'},
        ),
    ]
