# Generated by Django 5.1.1 on 2024-11-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_standard_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
