# Generated by Django 5.1.1 on 2024-10-19 07:12

import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('send_to_all', models.BooleanField(default=False, verbose_name='ارسال به همه')),
                ('title', models.CharField(max_length=256, verbose_name='عنوان اعلان')),
                ('text', models.TextField(verbose_name='متن اعلان')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلانات',
            },
        ),
        migrations.CreateModel(
            name='NotificationPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('card_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان کادر')),
                ('card_description', models.TextField(blank=True, null=True, verbose_name='توضیحات کادر')),
            ],
            options={
                'verbose_name': 'صفحه اعلانات',
                'verbose_name_plural': 'مدیرت صفحه اعلانات',
            },
        ),
    ]
