# Generated by Django 5.1.1 on 2024-10-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_read_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
