# Generated by Django 5.1.1 on 2024-10-17 12:03

import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('send_to_all', models.BooleanField(default=False, verbose_name='ارسال به همه')),
                ('title', models.CharField(max_length=256, verbose_name='عنوان اعلان')),
                ('text', models.TextField(verbose_name='متن اعلان')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('read_users', models.ManyToManyField(blank=True, related_name='readers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلانات',
            },
        ),
    ]
