# Generated by Django 5.1.1 on 2024-09-17 11:06

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='نام شبکه اجتماعی')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='Marketer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='نام و نام خانوادگی')),
                ('image', models.ImageField(upload_to='marketing/marketer/profile/', verbose_name='عکس پروفایل')),
                ('active_phone', models.SlugField(max_length=11, unique=True, verbose_name='شماره تماس فعال')),
                ('social_phone', models.SlugField(max_length=11, unique=True, verbose_name='شماره شبکه اجتماعی')),
                ('authenticated_code', models.SlugField(blank=True, null=True, verbose_name='کد معرف')),
                ('time_work', models.CharField(choices=[('full-time', 'تمام وقت'), ('part-time', 'پاره وقت')], default='part-time', max_length=10, verbose_name='مدت زمان کار')),
                ('start_time_work', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع کار')),
                ('end_time_work', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان کار')),
                ('type', models.CharField(choices=[('phone', 'تلفنی'), ('internet', 'اینترنتی'), ('presence', 'حضوری')], default='phone', max_length=10, verbose_name='نوع بازاریاب')),
                ('national_id', models.PositiveBigIntegerField(verbose_name='کد ملی')),
                ('percent', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='درصد بازاریاب')),
                ('discount_percent', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='درصد تخفیف بازاریاب')),
                ('social_media', models.ManyToManyField(to='marketing.socialmedia', verbose_name='شبکه اجتماعی')),
            ],
            options={
                'verbose_name': 'بازاریاب',
                'verbose_name_plural': 'بازاریاب ها',
            },
        ),
    ]
