# Generated by Django 5.1.1 on 2024-09-14 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketer',
            options={'verbose_name': 'بازاریاب', 'verbose_name_plural': 'بازاریاب ها'},
        ),
        migrations.AlterField(
            model_name='marketer',
            name='discount_percent',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='درصد تخفیف بازاریاب'),
        ),
    ]
