# Generated by Django 5.1.1 on 2024-09-24 12:16

import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('background_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان روی بک گراند')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='blog/background/', verbose_name='بک گراند')),
            ],
            options={
                'verbose_name': 'صفحه بلاگ ها',
                'verbose_name_plural': 'مدیرت صفحه بلاگ ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'دسته بندی بلاگ',
                'verbose_name_plural': 'دسته بندی های بلاگ',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='عنوان مقاله')),
                ('author', models.CharField(max_length=256, verbose_name='نویسنده')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('description', models.TextField(verbose_name='توضیحات مقاله')),
                ('created_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('cover', models.ImageField(upload_to='blog/cover', verbose_name='کاور بلاگ')),
                ('is_published', models.BooleanField(default=False, verbose_name='ایا انتشار شده است')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='نام و نام خانوادگی')),
                ('phone', models.SlugField(verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_valid', models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog', verbose_name='بلاگ')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='blog.comment', verbose_name='پاسخ به')),
            ],
            options={
                'verbose_name': 'کامنت ',
                'verbose_name_plural': 'کامنت های بلاگ',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/module/image/', verbose_name='تصویر')),
                ('file', models.FileField(blank=True, null=True, upload_to='blog/module/file/', verbose_name='فایل')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='blog.blog', verbose_name='بلاگ')),
            ],
        ),
    ]
