# Generated by Django 5.1.1 on 2024-11-08 12:26

import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='عنوان مقاله')),
                ('author', models.CharField(max_length=256, verbose_name='نویسنده')),
                ('code', models.SlugField(blank=True, null=True, verbose_name='کد بلاگ')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('description', models.TextField(verbose_name='توضیحات مقاله')),
                ('created_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('cover', models.ImageField(upload_to='blog/cover', verbose_name='کاور بلاگ')),
                ('is_published', models.BooleanField(default=False, verbose_name='ایا انتشار شده است')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'دسته بندی بلاگ',
                'verbose_name_plural': 'دسته بندی های بلاگ',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('is_from_admin', models.BooleanField(default=False, verbose_name='از طرف ادمین')),
                ('reply_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='رپلای به چه کسی')),
                ('description', models.TextField(verbose_name='پیام کاربر')),
                ('is_valid', models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'کامنت ',
                'verbose_name_plural': 'کامنت های بلاگ',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='نام برچسب')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
            },
        ),
        migrations.CreateModel(
            name='ViolationComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('topic', models.CharField(max_length=256, verbose_name='موضوع')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'گزارش تخلف کامنت',
                'verbose_name_plural': 'گزارشات تخلف کامنت ها',
            },
        ),
    ]
