# Generated by Django 5.1.1 on 2024-09-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='phone',
            field=models.SlugField(default=None, verbose_name='شماره تلفن'),
            preserve_default=False,
        ),
    ]
