# Generated by Django 5.1.1 on 2024-10-16 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='blog_comment_dislikeds', to=settings.AUTH_USER_MODEL, verbose_name='دیس لایک شده توسط'),
        ),
        migrations.AddField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='blog_comment_likeds', to=settings.AUTH_USER_MODEL, verbose_name='لایک شده توسط'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='blog.comment'),
        ),
        migrations.AddField(
            model_name='module',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='blog.blog', verbose_name='بلاگ'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='برچسب'),
        ),
        migrations.AddField(
            model_name='violationcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='blog.comment', verbose_name='کامنت'),
        ),
    ]
