# Generated by Django 5.1.1 on 2024-10-08 12:08

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='file',
        ),
        migrations.RemoveField(
            model_name='module',
            name='image',
        ),
        migrations.AlterField(
            model_name='module',
            name='text',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='متن'),
        ),
    ]
