# Generated by Django 5.1.1 on 2024-10-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_module_file_remove_module_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='blog/module/file/', verbose_name='فایل'),
        ),
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/module/image/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='module',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='متن'),
        ),
    ]
