# Generated by Django 5.1.1 on 2024-10-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='code',
            field=models.SlugField(blank=True, null=True, verbose_name='کد بلاگ'),
        ),
    ]
