# Generated by Django 5.1.1 on 2024-09-20 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('background_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان روی بک گراند')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='blog/background/', verbose_name='بک گراند')),
            ],
            options={
                'verbose_name': 'صفحه بلاگ ها',
                'verbose_name_plural': 'مدیرت صفحه بلاگ ها',
            },
        ),
    ]
