# Generated by Django 5.1 on 2024-11-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_comment_phone_alter_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='رپلای به چه کسی'),
        ),
    ]
