# Generated by Django 5.1.1 on 2024-10-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_module_file_module_image_alter_module_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='file',
        ),
        migrations.RemoveField(
            model_name='module',
            name='image',
        ),
    ]
