# Generated by Django 5.1.1 on 2024-11-10 11:29

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
    ]
