# Generated by Django 5.1.1 on 2024-10-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_module_file_remove_module_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='url',
        ),
    ]
