# Generated by Django 5.1.1 on 2024-09-18 08:39

import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان دستاورد های ما ')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان زیر ')),
            ],
            options={
                'verbose_name': 'عنوان دستاورد',
                'verbose_name_plural': 'مدیریت عنوان دستاورد ها',
            },
        ),
        migrations.CreateModel(
            name='AnswerQuestionTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان فرم تماس')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان پایینی فرم تماس')),
                ('image', models.ImageField(blank=True, null=True, upload_to='answer/image/', verbose_name='تصویر کادر زرد')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن کادر زرد')),
                ('phone_1', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='شماره تماس ۱')),
                ('phone_2', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='شماره تماس ۲')),
                ('phone_3', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='شماره تماس ۳')),
            ],
            options={
                'verbose_name': 'مدیرت سوالات مشتری',
                'verbose_name_plural': 'مدیرت سوالات مشتری',
            },
        ),
        migrations.CreateModel(
            name='BlogTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان مقاله')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='زیر عنوان مقاله')),
            ],
            options={
                'verbose_name': 'عنوان بلاگ',
                'verbose_name_plural': 'مدیرت عنوان بلاگ',
            },
        ),
        migrations.CreateModel(
            name='CommingSoon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان صفحه')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='template/commingsoon/', verbose_name='بک گراند صفحه')),
                ('time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال است')),
            ],
            options={
                'verbose_name': 'Comming Soon',
                'verbose_name_plural': 'مدیرت Comming Soon',
            },
        ),
        migrations.CreateModel(
            name='FirstPageContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان گواهینامه')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='زیر عنوان گواهینامه')),
                ('side_image', models.ImageField(upload_to='first_page_content/side_image/', verbose_name='عکس کنار گواهینامه ')),
                ('pattern_image', models.ImageField(blank=True, null=True, upload_to='first_page_content/pattern_image/', verbose_name='عکس پترن')),
            ],
            options={
                'verbose_name': 'محتوای صفحه اول',
                'verbose_name_plural': 'مدیرت محتوای صفحه اول',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='header/logo/', verbose_name='لوگو سایت')),
                ('phone', models.SlugField(blank=True, null=True, verbose_name='شماره تلفن داخل هدر')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل داخل هدر')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='header/icon/', verbose_name='آیکون کنار شماره و ایمیل در هدر')),
            ],
            options={
                'verbose_name': 'هدر',
                'verbose_name_plural': 'مدیرت هدر',
            },
        ),
        migrations.CreateModel(
            name='ProductTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان محصولات')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان زیر محصولات')),
            ],
            options={
                'verbose_name': 'عنوان صفحه محصولات',
                'verbose_name_plural': 'مدیرت عنوان صفحه محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProjectTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان پروژه ها ')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان کامنت مشتری ')),
            ],
            options={
                'verbose_name': ' عنوان پروژه و زیر عنوان',
                'verbose_name_plural': 'مدیرت عنوان پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title_slider', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان اسلایدر')),
                ('text_slider', models.TextField(blank=True, null=True, verbose_name='متن اسلایدر')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='توضیحات مختصر و مفید')),
                ('link_slider', models.URLField(blank=True, null=True, verbose_name='لینک دکمه اطلاعات بیشتر')),
            ],
            options={
                'verbose_name': 'اسلایدر صفحه هوم',
                'verbose_name_plural': 'مدیرت اسلایدر صفحه هوم',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256, verbose_name='عنوان')),
                ('logo', models.ImageField(upload_to='home/license/logo/', verbose_name='لوگو گواهینامه')),
                ('sub_title', models.CharField(max_length=256, verbose_name='زیر عنوان')),
                ('content_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='template.firstpagecontent')),
            ],
            options={
                'verbose_name': 'گواهی نامه',
                'verbose_name_plural': 'گواهی نامه ها',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='نام منو')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='template.header')),
            ],
            options={
                'verbose_name': 'منو',
                'verbose_name_plural': 'مدیرت منو  هدر',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('profile_user', models.ImageField(upload_to='template/commnet/profile/', verbose_name='پروفایل کاربر')),
                ('username', models.CharField(max_length=256, verbose_name='نام مشتری')),
                ('position', models.CharField(max_length=256, verbose_name='سمت مشتری')),
                ('text', models.TextField(verbose_name='نظر مشتری')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='template.projecttitle')),
            ],
            options={
                'verbose_name': 'کامنت مشتری ',
                'verbose_name_plural': 'مدیرت کامنت های مشتری ',
            },
        ),
        migrations.CreateModel(
            name='ImageSlider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='company/images/', verbose_name='تصویر')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='template.slider')),
            ],
            options={
                'verbose_name': 'تصویر اسلایدر ',
                'verbose_name_plural': 'تصاویر اسلایدر ',
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='زیر منو')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_menus', to='template.menu')),
            ],
            options={
                'verbose_name': 'زیر منو',
                'verbose_name_plural': 'زیر منو ها',
            },
        ),
    ]
