# Generated by Django 5.1.1 on 2024-09-16 14:20

import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommnetTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('profile_user', models.ImageField(upload_to='template/commnet/profile/', verbose_name='پروفایل کاربر')),
                ('username', models.CharField(max_length=256, verbose_name='نام مشتری')),
                ('position', models.CharField(max_length=256, verbose_name='سمت مشتری')),
                ('text', models.TextField(verbose_name='نظر مشتری')),
            ],
            options={
                'verbose_name': 'کامنت ',
                'verbose_name_plural': 'مدیرت کامنت ها',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='نام منو')),
            ],
            options={
                'verbose_name': 'منو',
                'verbose_name_plural': 'مدیرت منو  هدر',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='template/logo/', verbose_name='لوگو سایت')),
                ('phone', models.SlugField(blank=True, null=True, verbose_name='شماره تلفن داخل هدر')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل داخل هدر')),
            ],
            options={
                'verbose_name': 'قالب',
                'verbose_name_plural': 'مدیرت قالب',
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='زیر منو')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_menus', to='template.menu')),
            ],
            options={
                'verbose_name': 'زیر منو',
                'verbose_name_plural': 'زیر منو ها',
            },
        ),
        migrations.CreateModel(
            name='ProjectTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256, verbose_name='عنوان پروژه ها ')),
                ('sub_title', models.CharField(max_length=256, verbose_name='عنوان کامنت مشتری ')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_title', to='template.template')),
            ],
            options={
                'verbose_name': 'عنوان پروژه',
                'verbose_name_plural': 'مدیرت عنوان پروژه ',
            },
        ),
        migrations.CreateModel(
            name='ProductTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256, verbose_name='عنوان محصولات')),
                ('text', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان زیر محصولات')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_title', to='template.template')),
            ],
            options={
                'verbose_name': 'عنوان صفحه محصولات',
                'verbose_name_plural': 'مدیرت عنوان صفحه محصولات',
            },
        ),
        migrations.CreateModel(
            name='CommingSoon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان صفحه')),
                ('background_image', models.ImageField(upload_to='template/commingsoon/', verbose_name='بک گراند صفحه')),
                ('time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال است')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comming_soon', to='template.template')),
            ],
            options={
                'verbose_name': 'صفحه بزودی',
                'verbose_name_plural': 'مدیرت صفحه بزودی',
            },
        ),
        migrations.CreateModel(
            name='BlogTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256, verbose_name='عنوان مقاله')),
                ('sub_title', models.CharField(max_length=256, verbose_name='زیر عنوان مقاله')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_title', to='template.template')),
            ],
            options={
                'verbose_name': 'عنوان بلاگ',
                'verbose_name_plural': 'مدیرت عنوان بلاگ',
            },
        ),
        migrations.CreateModel(
            name='AnswerQuestionTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256, verbose_name='عنوان فرم تماس')),
                ('sub_title', models.CharField(max_length=256, verbose_name='عنوان پایینی فرم تماس')),
                ('image', models.ImageField(blank=True, null=True, upload_to='answer/image/', verbose_name='تصویر کادر زرد')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن کادر زرد')),
                ('phone_1', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='شماره تماس ۱')),
                ('phone_2', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='شماره تماس ۲')),
                ('phone_3', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='شماره تماس ۳')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answe', to='template.template')),
            ],
        ),
        migrations.CreateModel(
            name='AchievementTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256, verbose_name='عنوان دستاورد های ما ')),
                ('sub_title', models.CharField(max_length=256, verbose_name='عنوان زیر ')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_title', to='template.template')),
            ],
            options={
                'verbose_name': 'عنوان دستاورد',
                'verbose_name_plural': 'مدیریت عنوان دستاورد ها',
            },
        ),
    ]
