# Generated by Django 5.1.1 on 2024-09-27 08:40

import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('product', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان دستاورد های ما ')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان زیر ')),
                ('icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='ایکون')),
            ],
            options={
                'verbose_name': 'کادر دستاورد',
                'verbose_name_plural': 'مدیریت کادر دستاورد ها',
            },
        ),
        migrations.CreateModel(
            name='AnswerQuestionTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان فرم تماس')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان پایینی فرم تماس')),
                ('icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='ایکون ')),
                ('box_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان باکس')),
                ('box_text', models.TextField(blank=True, null=True, verbose_name='متن باکس')),
                ('image', models.ImageField(blank=True, null=True, upload_to='answer/image/', verbose_name='تصویر کادر زرد')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن کادر زرد')),
                ('icon_phone', models.CharField(blank=True, max_length=256, null=True, verbose_name='آیکون قسمت شماره ها')),
            ],
            options={
                'verbose_name': 'مدیرت سوالات مشتری',
                'verbose_name_plural': 'مدیرت باکس درخواست مشاوره',
            },
        ),
        migrations.CreateModel(
            name='CommingSoon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='template/commingsoon/logo/', verbose_name='لوگو')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان صفحه')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='زیر عنوان')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='template/commingsoon/', verbose_name='بک گراند صفحه')),
                ('time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان')),
                ('copy_right_text', models.TextField(blank=True, null=True, verbose_name='متن کپی رایت')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال است')),
            ],
            options={
                'verbose_name': 'Comming Soon',
                'verbose_name_plural': 'مدیرت Comming Soon',
            },
        ),
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='نام و نام خانوادگی')),
                ('person', models.CharField(choices=[('real', 'حقیقی'), ('legal', 'حقوقی')], default='real', max_length=5)),
                ('phone', models.SlugField(max_length=11, verbose_name='شماره همراه')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('is_valid', models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره ',
                'verbose_name_plural': 'درخواست های مشاوره کاربران',
            },
        ),
        migrations.CreateModel(
            name='CustomerClub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('phone', models.SlugField(verbose_name='شماره')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'باشگاه مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='template/footer/logo/', verbose_name='لوگو ')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن فوتر')),
                ('link_footer_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان ستون لینک ها')),
                ('category_footer_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان ستون دسته بندی ها')),
                ('copyright_text', models.TextField(blank=True, null=True, verbose_name='متن کپی رایت')),
            ],
            options={
                'verbose_name': 'فوتر',
                'verbose_name_plural': 'فوتر',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='header/logo/', verbose_name='لوگو سایت')),
                ('phone', models.SlugField(blank=True, null=True, verbose_name='شماره تلفن داخل هدر')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل داخل هدر')),
                ('icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='آیکون کنار شماره و ایمیل در هدر')),
            ],
            options={
                'verbose_name': 'هدر',
                'verbose_name_plural': 'مدیرت هدر',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256, verbose_name='عنوان')),
                ('logo', models.ImageField(upload_to='home/license/logo/', verbose_name='لوگو گواهینامه')),
                ('sub_title', models.CharField(max_length=256, verbose_name='زیر عنوان')),
            ],
            options={
                'verbose_name': 'گواهی نامه',
                'verbose_name_plural': 'گواهی نامه ها',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان پایین')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن اسلاید')),
                ('image', models.ImageField(upload_to='template/slider/image/', verbose_name='تصویر اسلاید')),
                ('button_text', models.CharField(blank=True, max_length=128, null=True, verbose_name='متن button')),
                ('link_slider', models.URLField(blank=True, null=True, verbose_name='لینک دکمه اطلاعات بیشتر')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'مدیرت اسلایدر',
            },
        ),
        migrations.CreateModel(
            name='AchievementCardItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(max_length=256, verbose_name='کلید')),
                ('value', models.CharField(max_length=256, verbose_name='مقدار')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='template.achievementcard')),
            ],
            options={
                'verbose_name': 'دستاورد',
                'verbose_name_plural': 'دستاورد ها',
            },
        ),
        migrations.CreateModel(
            name='BlogTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان مقاله')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='زیر عنوان مقاله')),
                ('icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='ایکون کادر مقاله')),
                ('button_text', models.CharField(blank=True, max_length=128, null=True, verbose_name='متن button')),
                ('button_url', models.CharField(blank=True, max_length=128, null=True, verbose_name='آدرس button')),
                ('blogs', models.ManyToManyField(blank=True, to='blog.blog', verbose_name='مقاله ها')),
            ],
            options={
                'verbose_name': 'کادر بلاگ',
                'verbose_name_plural': 'مدیرت کادر بلاگ',
            },
        ),
        migrations.CreateModel(
            name='ElectroLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='template/footer/image/', verbose_name='تصویر')),
                ('url', models.URLField(blank=True, null=True, verbose_name='آدرس')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='template.footer')),
            ],
            options={
                'verbose_name': 'مجوز فوتر ',
                'verbose_name_plural': 'مجوز های فوتر',
            },
        ),
        migrations.CreateModel(
            name='CategoryFooter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='نام دسته بندی')),
                ('url', models.URLField(verbose_name='آدرس دسته بندی')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_category', to='template.footer')),
            ],
            options={
                'verbose_name': 'دسته بندی فوتر',
                'verbose_name_plural': 'دسته بندی های فوتر ',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='نام لینک')),
                ('internal_url', models.URLField(blank=True, null=True, verbose_name='ادرس داخلی')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='ادرس خارجی')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='template.footer')),
            ],
            options={
                'verbose_name': 'لینک فوتر',
                'verbose_name_plural': 'لینک های فوتر',
            },
        ),
        migrations.CreateModel(
            name='FirstPageContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان گواهینامه')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='زیر عنوان گواهینامه')),
                ('side_image', models.ImageField(upload_to='first_page_content/side_image/', verbose_name='عکس کنار گواهینامه ')),
                ('button_text', models.CharField(blank=True, max_length=128, null=True, verbose_name='متن button')),
                ('pattern_image', models.ImageField(blank=True, null=True, upload_to='first_page_content/pattern_image/', verbose_name='عکس پترن')),
                ('licenses', models.ManyToManyField(blank=True, to='template.license', verbose_name='گواهینامه ها')),
            ],
            options={
                'verbose_name': 'محتوای صفحه اول',
                'verbose_name_plural': 'مدیرت محتوای صفحه اول',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='نام منو')),
                ('internal_url', models.URLField(blank=True, null=True, verbose_name='لینک داخلی')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='لینک خارجی')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='template.header')),
            ],
            options={
                'verbose_name': 'منو',
                'verbose_name_plural': 'مدیرت منو  هدر',
            },
        ),
        migrations.CreateModel(
            name='PhoneAnswerQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='template.answerquestiontitle')),
            ],
            options={
                'verbose_name': 'شماره',
                'verbose_name_plural': 'شماره ها',
            },
        ),
        migrations.CreateModel(
            name='PhoneFooter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='آیکون')),
                ('phone', models.CharField(max_length=256, verbose_name='شماره')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_phones', to='template.footer')),
            ],
            options={
                'verbose_name': 'شماره تلفن فوتر',
                'verbose_name_plural': 'شماره های فوتر',
            },
        ),
        migrations.CreateModel(
            name='ProductTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان محصولات')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان زیر محصولات')),
                ('icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='ایکون کادر')),
                ('button_text', models.CharField(blank=True, max_length=128, null=True, verbose_name='متن button')),
                ('button_url', models.URLField(blank=True, null=True, verbose_name='آدرس button')),
                ('categories', models.ManyToManyField(blank=True, to='product.category', verbose_name='دسته بندی های محصول')),
            ],
            options={
                'verbose_name': 'کادر محصولات',
                'verbose_name_plural': 'مدیرت کادر محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProjectTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان پروژه ها ')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان کامنت مشتری ')),
                ('button_text', models.CharField(blank=True, max_length=128, null=True, verbose_name='متن button')),
                ('button_url', models.URLField(blank=True, null=True, verbose_name='آدرس button')),
                ('icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='ایکون کادر پروژه ها')),
                ('category_projects', models.ManyToManyField(blank=True, to='project.category', verbose_name='دسته بندی های پروژه')),
            ],
            options={
                'verbose_name': ' کادر پروژه',
                'verbose_name_plural': 'مدیرت کادر پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان کامنت')),
                ('profile_user', models.ImageField(upload_to='template/commnet/profile/', verbose_name='پروفایل کاربر')),
                ('username', models.CharField(max_length=256, verbose_name='نام مشتری')),
                ('position', models.CharField(max_length=256, verbose_name='سمت مشتری')),
                ('text', models.TextField(verbose_name='نظر مشتری')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='template.projecttitle')),
            ],
            options={
                'verbose_name': 'کامنت مشتری ',
                'verbose_name_plural': 'مدیرت کامنت های مشتری ',
            },
        ),
        migrations.CreateModel(
            name='SocialFooter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='آیکون')),
                ('url', models.URLField(verbose_name='آدرس')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_socials', to='template.footer')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی فوتر',
                'verbose_name_plural': 'شبکه های اجتماعی فوتر',
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='زیر منو')),
                ('interal_url', models.URLField(blank=True, null=True, verbose_name='لینک داخلی ')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='لینک خارجی')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_menus', to='template.menu')),
            ],
            options={
                'verbose_name': 'زیر منو',
                'verbose_name_plural': 'زیر منو ها',
            },
        ),
    ]
