# Generated by Django 5.1.1 on 2024-09-22 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=256, verbose_name='نام')),
                ('last_name', models.CharField(max_length=256, verbose_name='نام خانوادگی')),
                ('phone', models.SlugField(max_length=11, verbose_name='شماره همراه')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('is_valid', models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره ',
                'verbose_name_plural': 'درخواست های مشاوره کاربران',
            },
        ),
    ]
