# Generated by Django 5.1.1 on 2024-09-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerquestiontitle',
            options={'verbose_name': 'مدیرت سوالات مشتری', 'verbose_name_plural': 'مدیرت کادر درخواست مشاوره'},
        ),
        migrations.RemoveField(
            model_name='consult',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='projecttitle',
            name='comment_title',
        ),
        migrations.AddField(
            model_name='answerquestiontitle',
            name='icon_phone',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='آیکون قسمت شماره ها'),
        ),
        migrations.AddField(
            model_name='blogtitle',
            name='button_text',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='متن button'),
        ),
        migrations.AddField(
            model_name='blogtitle',
            name='button_url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='آدرس button'),
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان کامنت'),
        ),
        migrations.AddField(
            model_name='consult',
            name='name',
            field=models.CharField(default=None, max_length=256, verbose_name='نام و نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consult',
            name='person',
            field=models.CharField(choices=[('حقیقی', 'real'), ('حقوقی', 'legal')], default='real', max_length=5),
        ),
        migrations.AddField(
            model_name='footer',
            name='category_footer_title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان ستون دسته بندی ها'),
        ),
        migrations.AddField(
            model_name='producttitle',
            name='button_text',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='متن button'),
        ),
        migrations.AddField(
            model_name='producttitle',
            name='button_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس button'),
        ),
        migrations.AddField(
            model_name='projecttitle',
            name='button_text',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='متن button'),
        ),
        migrations.AddField(
            model_name='projecttitle',
            name='button_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس button'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='link_footer_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان ستون لینک ها'),
        ),
    ]
