# Generated by Django 5.1.1 on 2024-09-28 08:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256, verbose_name='عنوان')),
                ('logo', models.ImageField(upload_to='home/license/logo/', verbose_name='لوگو گواهینامه')),
                ('text', models.TextField(verbose_name='متن دستاورد')),
            ],
            options={
                'verbose_name': 'دستاورد  ',
                'verbose_name_plural': 'دستاورد',
            },
        ),
        migrations.CreateModel(
            name='AchievementTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان')),
                ('icon', models.CharField(blank=True, max_length=128, unique=True, verbose_name='آیکون')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
            ],
            options={
                'verbose_name': 'پاپ آپ دستاورد ها',
                'verbose_name_plural': 'مدیریت پاپ آپ دستاورد ها',
            },
        ),
        migrations.RemoveField(
            model_name='firstpagecontent',
            name='licenses',
        ),
        migrations.AddField(
            model_name='firstpagecontent',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='template.achievement', verbose_name='دستاورد ها '),
        ),
        migrations.AddField(
            model_name='achievement',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='template.achievementtitle'),
        ),
        migrations.DeleteModel(
            name='License',
        ),
    ]
