# Generated by Django 5.1.1 on 2024-10-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonefooter',
            name='is_constant',
            field=models.BooleanField(default=False, verbose_name='شماره ثابت است'),
        ),
        migrations.AddField(
            model_name='phonefooter',
            name='is_fax',
            field=models.BooleanField(default=False, verbose_name='شماره فکس است'),
        ),
    ]
