# Generated by Django 5.1.1 on 2024-10-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='person',
            field=models.CharField(choices=[('real', 'حقیقی'), ('legal', 'حقوقی')], default='real', max_length=5, verbose_name='شخص'),
        ),
    ]
