# Generated by Django 5.1.1 on 2024-10-27 04:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256, verbose_name='عنوان کادر')),
                ('text', models.TextField(verbose_name='متن کادر')),
            ],
            options={
                'verbose_name': 'صفحه ذخیره شده ها',
                'verbose_name_plural': 'صفحه ذخیره شده ها',
            },
        ),
    ]
