# Generated by Django 5.1.1 on 2024-11-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='logo_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان لوگو'),
        ),
    ]
