# Generated by Django 5.1.1 on 2024-10-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementcard',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='achievementtitle',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='answerquestiontitle',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='answerquestiontitle',
            name='icon_phone',
        ),
        migrations.RemoveField(
            model_name='blogtitle',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='header',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='phonefooter',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='producttitle',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='projecttitle',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='socialfooter',
            name='icon',
        ),
    ]
