# Generated by Django 5.1.1 on 2024-10-15 09:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCardsPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان کادر')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن کادر')),
            ],
            options={
                'verbose_name': 'صفحه شماره کارت های شرکت',
                'verbose_name_plural': 'صفحه شماره کارت های شرکت',
            },
        ),
        migrations.CreateModel(
            name='CompanyCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('bank_name', models.CharField(max_length=256, verbose_name='نام بانک')),
                ('bank_icon', models.ImageField(blank=True, null=True, upload_to='template/company-page/', verbose_name='آیکون بانک')),
                ('card_number', models.SlugField(verbose_name='شماره کارت')),
                ('sheba_number', models.SlugField(verbose_name='شماره شبا')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='template.companycardspage')),
            ],
            options={
                'verbose_name': 'شماره کارت',
                'verbose_name_plural': 'شماره کارت های شرکت',
            },
        ),
    ]
