# Generated by Django 5.1.1 on 2024-09-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtitle',
            name='template',
        ),
        migrations.AlterField(
            model_name='achievementtitle',
            name='sub_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان زیر '),
        ),
        migrations.AlterField(
            model_name='achievementtitle',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان دستاورد های ما '),
        ),
        migrations.AlterField(
            model_name='answerquestiontitle',
            name='sub_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان پایینی فرم تماس'),
        ),
        migrations.AlterField(
            model_name='answerquestiontitle',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان فرم تماس'),
        ),
        migrations.AlterField(
            model_name='blogtitle',
            name='sub_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='زیر عنوان مقاله'),
        ),
        migrations.AlterField(
            model_name='blogtitle',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان مقاله'),
        ),
        migrations.AlterField(
            model_name='commingsoon',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='template/commingsoon/', verbose_name='بک گراند صفحه'),
        ),
        migrations.AlterField(
            model_name='producttitle',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان محصولات'),
        ),
        migrations.AlterField(
            model_name='projecttitle',
            name='sub_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان کامنت مشتری '),
        ),
        migrations.AlterField(
            model_name='projecttitle',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان پروژه ها '),
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
