# Generated by Django 5.1.1 on 2024-10-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryfooter',
            options={'verbose_name': 'لینک فوتر', 'verbose_name_plural': 'لینک های فوتر ستون ۲'},
        ),
        migrations.AlterModelOptions(
            name='footerlink',
            options={'verbose_name': 'لینک فوتر', 'verbose_name_plural': 'لینک های فوتر ستون ۱'},
        ),
        migrations.AddField(
            model_name='footer',
            name='inamad_code',
            field=models.TextField(blank=True, null=True, verbose_name='کد اینماد'),
        ),
        migrations.AlterField(
            model_name='categoryfooter',
            name='name',
            field=models.CharField(max_length=256, verbose_name='نام لینک'),
        ),
        migrations.AlterField(
            model_name='categoryfooter',
            name='url',
            field=models.URLField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='category_footer_title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان ستون لینک ها ۲'),
        ),
    ]
