# Generated by Django 5.1.1 on 2024-11-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_footer_logo_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerfeq',
            options={'ordering': ['created'], 'verbose_name': 'سوال فوتر', 'verbose_name_plural': 'سوالات متداول فوتر'},
        ),
        migrations.AddField(
            model_name='footerfeq',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
