# Generated by Django 5.1.1 on 2024-10-10 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_alter_consult_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
        migrations.CreateModel(
            name='FooterFeq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=256, verbose_name='سوال')),
                ('response', models.TextField(verbose_name='پاسخ')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feqs', to='template.footer')),
            ],
            options={
                'verbose_name': 'سوال فوتر',
                'verbose_name_plural': 'سوالات متداول فوتر',
            },
        ),
    ]
