# Generated by Django 5.1.1 on 2024-09-27 07:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_alter_answerquestiontitle_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerquestiontitle',
            name='phone_1',
        ),
        migrations.RemoveField(
            model_name='answerquestiontitle',
            name='phone_2',
        ),
        migrations.RemoveField(
            model_name='answerquestiontitle',
            name='phone_3',
        ),
        migrations.RemoveField(
            model_name='license',
            name='content_page',
        ),
        migrations.AddField(
            model_name='answerquestiontitle',
            name='box_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن باکس'),
        ),
        migrations.AddField(
            model_name='answerquestiontitle',
            name='box_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان باکس'),
        ),
        migrations.AddField(
            model_name='firstpagecontent',
            name='button_text',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='متن button'),
        ),
        migrations.AddField(
            model_name='firstpagecontent',
            name='licenses',
            field=models.ManyToManyField(blank=True, to='template.license', verbose_name='گواهینامه ها'),
        ),
        migrations.AlterField(
            model_name='answerquestiontitle',
            name='icon',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='ایکون '),
        ),
        migrations.CreateModel(
            name='PhoneAnswerQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='template.answerquestiontitle')),
            ],
            options={
                'verbose_name': 'شماره',
                'verbose_name_plural': 'شماره ها',
            },
        ),
    ]
