# Generated by Django 5.1.1 on 2024-10-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_phonefooter_is_constant_phonefooter_is_fax'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='eitaa_link',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس ایتا'),
        ),
        migrations.AddField(
            model_name='footer',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس اینستاگرام'),
        ),
        migrations.AddField(
            model_name='footer',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس لینکدین'),
        ),
        migrations.AddField(
            model_name='footer',
            name='soroush_link',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس سروش'),
        ),
        migrations.AddField(
            model_name='footer',
            name='telegram_link',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس تلگرام'),
        ),
        migrations.DeleteModel(
            name='SocialFooter',
        ),
    ]
