# Generated by Django 5.1.1 on 2024-10-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_achievement_achievementtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='آیکون کنار شماره و ایمیل در هدر'),
        ),
    ]
