# Generated by Django 5.1.1 on 2024-10-29 11:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_savedpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('logo', models.CharField(blank=True, max_length=256, null=True, verbose_name='لوگو')),
                ('text', models.CharField(blank=True, max_length=450, null=True, verbose_name='متن زیر دکمه')),
            ],
            options={
                'verbose_name': 'صفحه لاگین',
                'verbose_name_plural': 'صفحه لاگین',
            },
        ),
        migrations.CreateModel(
            name='LoginPageSlide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='template/login/slider/', verbose_name='تصویر')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='template.loginpage')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلاید ها',
            },
        ),
    ]
