# Generated by Django 5.1.1 on 2024-09-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_remove_answerquestiontitle_phone_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageSlider',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
