# Generated by Django 5.1.1 on 2024-10-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_alter_consult_is_valid_footerfeq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerfeq',
            old_name='response',
            new_name='answer',
        ),
    ]
