# Generated by Django 5.1.1 on 2024-10-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_alter_header_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementcard',
            name='icon',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='ایکون'),
        ),
        migrations.AlterField(
            model_name='achievementtitle',
            name='icon',
            field=models.ImageField(blank=True, max_length=128, unique=True, upload_to='', verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='answerquestiontitle',
            name='icon',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='ایکون '),
        ),
        migrations.AlterField(
            model_name='answerquestiontitle',
            name='icon_phone',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='آیکون قسمت شماره ها'),
        ),
        migrations.AlterField(
            model_name='blogtitle',
            name='icon',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='ایکون کادر مقاله'),
        ),
        migrations.AlterField(
            model_name='phonefooter',
            name='icon',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='producttitle',
            name='icon',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='ایکون کادر'),
        ),
        migrations.AlterField(
            model_name='projecttitle',
            name='icon',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='ایکون کادر پروژه ها'),
        ),
        migrations.AlterField(
            model_name='socialfooter',
            name='icon',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='آیکون'),
        ),
    ]
