# Generated by Django 5.1.1 on 2024-10-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_footer_eitaa_link_footer_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='internal_url',
            field=models.SlugField(blank=True, null=True, verbose_name='لینک داخلی'),
        ),
    ]
