# Generated by Django 5.1.1 on 2024-10-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_loginpage_loginpageslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginpage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='template/login', verbose_name='لوگو'),
        ),
    ]
