# Generated by Django 5.1.1 on 2024-11-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_alter_footerfeq_options_footerfeq_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='logo_sub_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='زیر عنوان لوگو'),
        ),
    ]
