# Generated by Django 5.1.1 on 2024-10-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_alter_loginpage_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerclub',
            name='phone',
            field=models.SlugField(unique=True, verbose_name='شماره'),
        ),
    ]
