# Generated by Django 5.1.1 on 2024-10-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_alter_menu_internal_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='internal_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='لینک داخلی'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='interal_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='لینک داخلی '),
        ),
    ]
