# Generated by Django 5.1.1 on 2024-11-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_footer_logo_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneanswerquestion',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان'),
        ),
    ]
