# Generated by Django 5.1.1 on 2024-10-10 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_rename_response_footerfeq_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfooter',
            name='footer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='template.footer'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='footer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='template.footer'),
        ),
        migrations.AlterField(
            model_name='phonefooter',
            name='footer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='template.footer'),
        ),
        migrations.AlterField(
            model_name='socialfooter',
            name='footer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='template.footer'),
        ),
    ]
