# Generated by Django 5.1.1 on 2024-09-27 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_delete_imageslider_delete_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان پایین')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن اسلاید')),
                ('image', models.ImageField(upload_to='template/slider/image/', verbose_name='تصویر اسلاید')),
                ('link_slider', models.URLField(blank=True, null=True, verbose_name='لینک دکمه اطلاعات بیشتر')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'مدیرت اسلایدر',
            },
        ),
    ]
