# Generated by Django 5.1.1 on 2024-09-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0005_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerquestiontitle',
            options={'verbose_name': 'مدیرت سوالات مشتری', 'verbose_name_plural': 'مدیرت باکس درخواست مشاوره'},
        ),
        migrations.AddField(
            model_name='slider',
            name='button_text',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='متن button'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='person',
            field=models.CharField(choices=[('real', 'حقیقی'), ('legal', 'حقوقی')], default='real', max_length=5),
        ),
    ]
