# Generated by Django 5.1.1 on 2024-10-11 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0005_alter_categoryfooter_footer_alter_footerlink_footer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstpagecontent',
            name='pattern_image',
        ),
    ]
