# Generated by Django 5.1.1 on 2024-10-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0006_remove_firstpagecontent_pattern_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstpagecontent',
            options={'verbose_name': 'گواهینامه های صفحه اصلی', 'verbose_name_plural': 'گواهینامه های صفحه اصلی'},
        ),
        migrations.AddField(
            model_name='socialfooter',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='نام شبکه اجتماعی'),
        ),
    ]
