# Generated by Django 5.1.1 on 2024-09-27 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactConsult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(verbose_name='نام')),
                ('department', models.CharField(max_length=256, verbose_name='دپارتمان')),
                ('phone', models.SlugField(verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('text', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره ',
                'verbose_name_plural': 'درخواست های مشاوره صفحه ارتباط با ما',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'صفحه تماس با ما',
                'verbose_name_plural': 'مدیرت صفحه تماس با ما',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.ManyToManyField(blank=True, to='project.project', verbose_name='پروژه های صفحه درباره ما')),
            ],
            options={
                'verbose_name': 'صفحه درباره ما',
                'verbose_name_plural': 'مدیرت صفحه درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان دستاورد ها ')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان پایینی')),
                ('icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='ایکون')),
                ('customer_count', models.PositiveIntegerField(verbose_name='تعداد مشتری ها ')),
                ('building', models.PositiveIntegerField(verbose_name='در حال ساخت')),
                ('checking', models.PositiveIntegerField(verbose_name='در حال بررسی')),
                ('complete', models.PositiveIntegerField(verbose_name='پروژه های تکمیلی')),
                ('about', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='config.aboutus')),
            ],
            options={
                'verbose_name': 'دستاورد',
                'verbose_name_plural': 'دستاورد های ما',
            },
        ),
        migrations.CreateModel(
            name='ContactTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان بالایی تماس با ما')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان پایینی تماس با ما')),
                ('icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='ایکون')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='config/contact-us/side-image/', verbose_name='تصویر کناری')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_title', to='config.contactus')),
            ],
            options={
                'verbose_name': 'عنوان کادر تماس با ما',
                'verbose_name_plural': 'عنوان کادر تماس با ما',
            },
        ),
        migrations.CreateModel(
            name='ContactItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(max_length=256, verbose_name='کلید')),
                ('value', models.CharField(max_length=256, verbose_name='مقدار')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_items', to='config.contactus')),
            ],
            options={
                'verbose_name': 'راه ارتباطی',
                'verbose_name_plural': 'راه های ارتباطی',
            },
        ),
        migrations.CreateModel(
            name='Feq',
            fields=[
                ('key', models.CharField(max_length=256, verbose_name='کلید')),
                ('value', models.CharField(max_length=256, verbose_name='مقدار')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feqs', to='config.aboutus')),
            ],
            options={
                'verbose_name': 'سوال ',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
        migrations.CreateModel(
            name='FeqTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان سوالات متداول')),
                ('icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='ایکون')),
                ('about', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feq_title', to='config.aboutus')),
            ],
            options={
                'verbose_name': 'عنوان سوالات متداول',
                'verbose_name_plural': 'عنوان سوالات متداول',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان کادر نقشه')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='زیر عنوان کادر نقشه')),
                ('icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='ایکون')),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='عرض جغرافیایی')),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='طول جغرافیایی')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='config.contactus')),
            ],
            options={
                'verbose_name': 'نقشه',
                'verbose_name_plural': 'مدیرت موقیعت مکانی',
            },
        ),
        migrations.CreateModel(
            name='OrderGuideTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان ثبت سفارش')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان پایینی')),
                ('icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='ایکون')),
                ('about', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_guide_title', to='config.aboutus')),
            ],
            options={
                'verbose_name': 'عنوان ثبت سفارش',
                'verbose_name_plural': 'عنوان ثبت سفارش',
            },
        ),
        migrations.CreateModel(
            name='OrderingGuide',
            fields=[
                ('key', models.CharField(max_length=256, verbose_name='کلید')),
                ('value', models.CharField(max_length=256, verbose_name='مقدار')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_items', to='config.aboutus')),
            ],
            options={
                'verbose_name': 'نحوه ثبت سفارش',
                'verbose_name_plural': 'راهنمای سفارش',
            },
        ),
        migrations.CreateModel(
            name='SocialContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='ایکون')),
                ('url', models.URLField(verbose_name='آدرس')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_social', to='config.contactus')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='SocialTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان بالایی شبکه های اجتماعی')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان پاینی شبکه های اجتماعی')),
                ('icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='ایکون')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_title', to='config.contactus')),
            ],
            options={
                'verbose_name': 'عنوان شبکه های اجتماعی',
                'verbose_name_plural': 'مدیرت عنوان شبکه های اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان بالا')),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان پایینی')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='about/story/side-image/', verbose_name='تصویر کناری')),
                ('text', models.TextField(verbose_name='داستان ما')),
                ('about', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='config.aboutus')),
            ],
            options={
                'verbose_name': 'داستان',
                'verbose_name_plural': 'داستان ما',
            },
        ),
        migrations.CreateModel(
            name='StoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=256, verbose_name='مقدار')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='config.story')),
            ],
            options={
                'verbose_name': 'آیتم داستان',
                'verbose_name_plural': 'آیتم های داستان',
            },
        ),
    ]
