# Generated by Django 5.1.1 on 2024-09-13 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/logo', verbose_name='لوگو')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات قسمت فوتر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='OrderingGuide',
            fields=[
                ('key', models.CharField(max_length=256, verbose_name='کلید')),
                ('value', models.TextField(verbose_name='مقدار')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordering_guide', to='config.settings')),
            ],
            options={
                'verbose_name': 'نحوه ثبت سفارش',
                'verbose_name_plural': 'راهنمای سفارش',
            },
        ),
        migrations.CreateModel(
            name='Feq',
            fields=[
                ('key', models.CharField(max_length=256, verbose_name='کلید')),
                ('value', models.TextField(verbose_name='مقدار')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feqs', to='config.settings')),
            ],
            options={
                'verbose_name': 'سوال ',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
        migrations.CreateModel(
            name='ContactItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(max_length=256, verbose_name='کلید')),
                ('value', models.TextField(verbose_name='مقدار')),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contact_items', to='config.settings')),
            ],
            options={
                'verbose_name': 'راه ارتباطی',
                'verbose_name_plural': 'راه های ارتباطی',
            },
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('customer_count', models.PositiveIntegerField(verbose_name='تعداد مشتری ها ')),
                ('building', models.PositiveIntegerField(verbose_name='در حال ساخت')),
                ('checking', models.PositiveIntegerField(verbose_name='در حال بررسی')),
                ('complete', models.PositiveIntegerField(verbose_name='پروژه های تکمیلی')),
                ('settings', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='config.settings')),
            ],
            options={
                'verbose_name': 'دستاورد',
                'verbose_name_plural': 'دستاورد های ما',
            },
        ),
        migrations.CreateModel(
            name='SocialContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='config/socials/', verbose_name='آیکون')),
                ('url', models.URLField(verbose_name='آدرس')),
                ('settings', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='config.settings')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(verbose_name='داستان ما')),
                ('settings', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='story', to='config.settings')),
            ],
            options={
                'verbose_name': 'داستان',
                'verbose_name_plural': 'داستان ما',
            },
        ),
    ]
