# Generated by Django 5.1.1 on 2024-10-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feq',
            name='key',
        ),
        migrations.RemoveField(
            model_name='feq',
            name='value',
        ),
        migrations.AddField(
            model_name='feq',
            name='answer',
            field=models.TextField(null=True, verbose_name='جواب'),
        ),
        migrations.AddField(
            model_name='feq',
            name='question',
            field=models.TextField(null=True, verbose_name='سوال'),
        ),
    ]
