# Generated by Django 5.1.1 on 2024-10-21 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='projects',
            field=models.ManyToManyField(blank=True, to='project.project', verbose_name='پروژه های صفحه درباره ما'),
        ),
        migrations.AddField(
            model_name='achievements',
            name='about',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='config.aboutus'),
        ),
        migrations.AddField(
            model_name='contacttitle',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_title', to='config.contactus'),
        ),
        migrations.AddField(
            model_name='contactitem',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_items', to='config.contactus'),
        ),
        migrations.AddField(
            model_name='feq',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feqs', to='config.aboutus'),
        ),
        migrations.AddField(
            model_name='feqtitle',
            name='about',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feq_title', to='config.aboutus'),
        ),
        migrations.AddField(
            model_name='location',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='config.contactus'),
        ),
        migrations.AddField(
            model_name='orderguidetitle',
            name='about',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_guide_title', to='config.aboutus'),
        ),
        migrations.AddField(
            model_name='orderingguide',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordering_items', to='config.aboutus'),
        ),
        migrations.AddField(
            model_name='socialcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_social', to='config.contactus'),
        ),
        migrations.AddField(
            model_name='socialtitle',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_title', to='config.contactus'),
        ),
        migrations.AddField(
            model_name='story',
            name='about',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='config.aboutus'),
        ),
        migrations.AddField(
            model_name='storyitem',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='config.story'),
        ),
    ]
