# Generated by Django 5.1.1 on 2024-09-20 07:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=256, verbose_name='مقدار')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='config.story')),
            ],
            options={
                'verbose_name': 'آیتم داستان',
                'verbose_name_plural': 'آیتم های داستان',
            },
        ),
    ]
