# Generated by Django 5.1.1 on 2024-10-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='icon',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='ایکون'),
        ),
        migrations.AlterField(
            model_name='contacttitle',
            name='icon',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='ایکون'),
        ),
        migrations.AlterField(
            model_name='feqtitle',
            name='icon',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='ایکون'),
        ),
        migrations.AlterField(
            model_name='location',
            name='icon',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='ایکون'),
        ),
        migrations.AlterField(
            model_name='orderguidetitle',
            name='icon',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='ایکون'),
        ),
        migrations.AlterField(
            model_name='socialcontact',
            name='icon',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='ایکون'),
        ),
        migrations.AlterField(
            model_name='socialtitle',
            name='icon',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='ایکون'),
        ),
    ]
