# Generated by Django 5.1.1 on 2024-09-22 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactConsult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(verbose_name='نام')),
                ('department', models.CharField(max_length=256, verbose_name='دپارتمان')),
                ('phone', models.SlugField(verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('text', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره ',
                'verbose_name_plural': 'درخواست های مشاوره صفحه ارتباط با ما',
            },
        ),
    ]
