# Generated by Django 5.1.1 on 2024-10-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='side_image',
        ),
    ]
