# Generated by Django 5.1.1 on 2024-09-25 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='background',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='background_title',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='background',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='background_title',
        ),
    ]
