# Generated by Django 5.1.1 on 2024-10-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_achievements_icon_alter_contacttitle_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactconsult',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
