# Generated by Django 5.1.1 on 2024-11-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='طول جغرافیایی'),
        ),
    ]
