# Generated by Django 5.1.1 on 2024-10-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactconsult',
            options={'verbose_name': 'درخواست مشاوره ', 'verbose_name_plural': 'درخواست های تماس با ما'},
        ),
    ]
