# Generated by Django 5.1.1 on 2024-11-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderingguide',
            options={'ordering': ['id'], 'verbose_name': 'نحوه ثبت سفارش', 'verbose_name_plural': 'راهنمای سفارش'},
        ),
        migrations.AlterField(
            model_name='orderingguide',
            name='value',
            field=models.TextField(verbose_name='مقدار'),
        ),
    ]
