# Generated by Django 5.1.1 on 2024-10-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='eitaa_link',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس ایتا'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس اینستاگرام'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس لینکدین'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='soroush_link',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس سروش'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='telegram_link',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس تلگرام'),
        ),
        migrations.DeleteModel(
            name='SocialContact',
        ),
    ]
