# Generated by Django 5.1.1 on 2024-10-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_remove_feq_key_remove_feq_value_feq_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactconsult',
            name='department',
            field=models.CharField(choices=[('legal', 'حقوقی'), ('personal', 'حقیقی')], max_length=256, verbose_name='دپارتمان'),
        ),
    ]
