# Generated by Django 5.1.1 on 2024-10-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_remove_story_side_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='side_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/story/side-image/', verbose_name='تصویر کناری'),
        ),
    ]
