# Generated by Django 5.1.1 on 2024-11-10 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_orderingguide_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderingguide',
            options={'ordering': ['created'], 'verbose_name': 'نحوه ثبت سفارش', 'verbose_name_plural': 'راهنمای سفارش'},
        ),
        migrations.AddField(
            model_name='orderingguide',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
