# Generated by Django 5.1.1 on 2024-10-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_contactconsult_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='contacttitle',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='feqtitle',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='location',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='orderguidetitle',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='socialcontact',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='socialtitle',
            name='icon',
        ),
    ]
