# Generated by Django 5.1.1 on 2024-11-10 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_orderingguide_options_orderingguide_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feq',
            options={'ordering': ['created'], 'verbose_name': 'سوال ', 'verbose_name_plural': 'سوالات متداول'},
        ),
        migrations.AddField(
            model_name='feq',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
