# Generated by Django 5.1.1 on 2024-11-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_feq_options_feq_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feq',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderingguide',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
