# Generated by Django 5.1.1 on 2024-09-16 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title_slider', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان اسلایدر')),
                ('text_slider', models.TextField(blank=True, null=True, verbose_name='متن اسلایدر')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='توضیحات مختصر و مفید')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'تنظمات صفحه هوم',
            },
        ),
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=256, verbose_name='نام')),
                ('last_name', models.CharField(max_length=256, verbose_name='نام خانوادگی')),
                ('phone', models.SlugField(max_length=11, verbose_name='شماره همراه')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('is_valid', models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره ',
                'verbose_name_plural': 'درخواست های مشاوره کاربران',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256, verbose_name='عنوان')),
                ('icon', models.ImageField(upload_to='home/license/icon/', verbose_name='آیکون گواهینامه')),
                ('description', models.TextField(verbose_name='توضیحات گواهینامه')),
            ],
            options={
                'verbose_name': 'گواهی نامه',
                'verbose_name_plural': 'گواهی نامه ها',
            },
        ),
        migrations.CreateModel(
            name='ImageCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='company/images/', verbose_name='تصویر')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.company')),
            ],
            options={
                'verbose_name': 'تصویر صفحه هوم',
                'verbose_name_plural': 'تصاویر صفحه هوم',
            },
        ),
    ]
