# Generated by Django 5.1.1 on 2024-09-27 08:40

import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('cover', models.ImageField(upload_to='category/cover/', verbose_name='کاور دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('project_card_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان کادر پروژه ها')),
                ('project_card_sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان زیر کادر پروژه ها')),
                ('project_card_icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='ایکون')),
            ],
            options={
                'verbose_name': 'صفحه پروژه ها',
                'verbose_name_plural': 'مدیرت صفحه پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('video', models.FileField(upload_to='project/video/', verbose_name='ویدیو پروژه')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='نام پروژه')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('description', models.TextField(verbose_name='توضیحات پروژه ')),
                ('contractor', models.CharField(max_length=256, verbose_name='نام پیمانکار')),
                ('launch_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ راه اندازی')),
                ('start_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ساخت')),
                ('location', models.CharField(max_length=256, verbose_name='موقیعت')),
                ('capacity', models.CharField(max_length=256, verbose_name='ظرفیت نامی')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.category', verbose_name='دسته بندی پروژه')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='نام و نام خانوادگی')),
                ('phone', models.SlugField(verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_valid', models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='project.comment', verbose_name='پاسخ به')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت های پروژه',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='project/images/', verbose_name='تصویر')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.project')),
            ],
            options={
                'verbose_name': 'تصویر پروژه',
                'verbose_name_plural': 'تصاویر پروژه',
            },
        ),
    ]
