# Generated by Django 5.1.1 on 2024-10-08 15:43

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='launch_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ راه اندازی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ساخت'),
            preserve_default=False,
        ),
    ]
