# Generated by Django 5.1.1 on 2024-10-07 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectspage',
            name='project_card_icon',
        ),
    ]
