# Generated by Django 5.1.1 on 2024-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspage',
            name='project_card_icon',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='ایکون'),
        ),
    ]
