# Generated by Django 5.1.1 on 2024-11-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='d',
            field=models.BooleanField(default=False),
        ),
    ]
