# Generated by Django 5.1.1 on 2024-10-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='phone',
            field=models.SlugField(blank=True, null=True, verbose_name='شماره تلفن'),
        ),
    ]
