# Generated by Django 5.1.1 on 2024-09-20 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_category_slug_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('background_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان بک گراند')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='project/background/', verbose_name='بک گراند')),
                ('project_card_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان کادر پروژه ها')),
                ('project_card_sub_title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان زیر کادر پروژه ها')),
                ('project_card_icon', models.ImageField(blank=True, max_length=256, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'صفحه پروژه ها',
                'verbose_name_plural': 'مدیرت صفحه پروژه ها',
            },
        ),
    ]
