# Generated by Django 5.1.1 on 2024-10-08 15:12

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_projectspage_project_card_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True, verbose_name='تاریخ ساخت'),
        ),
    ]
