# Generated by Django 5.1.1 on 2024-11-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='d',
        ),
    ]
