# Generated by Django 5.1.1 on 2024-10-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='project/images/', verbose_name='تصویر شاخص پروژه'),
        ),
    ]
