# Generated by Django 5.1 on 2024-11-04 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_comment_reply_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت های پروژه'},
        ),
    ]
