# Generated by Django 5.1.1 on 2024-10-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='card_title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان کادر'),
        ),
    ]
