# Generated by Django 5.1.1 on 2024-10-08 15:59

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_launch_date_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='launch_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ راه اندازی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ساخت'),
        ),
    ]
