# Generated by Django 5.1.1 on 2024-10-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_image_alter_project_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='project/image/', verbose_name='تصویر اصلی'),
        ),
    ]
