# Generated by Django 5.1.1 on 2024-10-09 13:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_project_image_project_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('video', models.FileField(upload_to='project/video/', verbose_name='فیلم')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='project.project')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'ویدیو های پروژه',
            },
        ),
    ]
