# Generated by Django 5.1.1 on 2024-10-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_videoproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='main_image',
        ),
    ]
