# Generated by Django 5.1.1 on 2024-10-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_project_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='d',
            field=models.BooleanField(default=False),
        ),
    ]
