# Generated by Django 5.1.1 on 2024-09-17 11:06

import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('ip', models.SlugField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('phone', models.SlugField(max_length=11, unique=True, verbose_name='موبایل')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='ادمین است / نیست')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_real', models.BooleanField(default=False, verbose_name='کاربر حقیقی')),
                ('is_legal', models.BooleanField(default=False, verbose_name='حقوقی')),
                ('otp_code', models.SlugField(blank=True, max_length=5, null=True, verbose_name='کد تایید')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='LegalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس پستی')),
                ('postal_code', models.PositiveBigIntegerField(verbose_name='کد پستی')),
                ('telephone', models.SlugField(verbose_name='تلفن ثابت')),
                ('social_phone', models.SlugField(verbose_name='شماره موبایل شبکه اجتماعی')),
                ('national_id', models.PositiveBigIntegerField(verbose_name='کد ملی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('name', models.CharField(max_length=256, verbose_name='نام شرکت')),
                ('economic_code', models.SlugField(verbose_name='کد اقتصادی')),
                ('foundation_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='سال تاسیس شرکت')),
                ('company_registration_number', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='شماره ثبت شرکت')),
                ('founder_company', models.CharField(blank=True, max_length=256, null=True, verbose_name='نام صاحب شرکت')),
                ('social_media', models.ManyToManyField(to='marketing.socialmedia', verbose_name='شبکه اجتماعی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل حقوقی',
                'verbose_name_plural': 'پروفایل حقوقی کاربر',
            },
        ),
        migrations.CreateModel(
            name='RealProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس پستی')),
                ('postal_code', models.PositiveBigIntegerField(verbose_name='کد پستی')),
                ('telephone', models.SlugField(verbose_name='تلفن ثابت')),
                ('social_phone', models.SlugField(verbose_name='شماره موبایل شبکه اجتماعی')),
                ('national_id', models.PositiveBigIntegerField(verbose_name='کد ملی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('name', models.CharField(max_length=256, verbose_name='نام و نام خانوادگی')),
                ('social_media', models.ManyToManyField(to='marketing.socialmedia', verbose_name='شبکه اجتماعی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='real_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل حقیقی',
            },
        ),
    ]
