# Generated by Django 5.1.1 on 2024-10-23 09:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0001_initial'),
        ('driver', '0001_initial'),
        ('product', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('ip', models.SlugField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='نام شبکه اجتماعی')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('phone', models.SlugField(max_length=11, unique=True, verbose_name='موبایل')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='ادمین است / نیست')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_real', models.BooleanField(default=False, verbose_name='کاربر حقیقی')),
                ('is_legal', models.BooleanField(default=False, verbose_name='حقوقی')),
                ('is_panel_active', models.BooleanField(default=False, verbose_name='پنل فعال است')),
                ('otp_code', models.SlugField(blank=True, max_length=5, null=True, verbose_name='کد تایید')),
                ('drivers', models.ManyToManyField(blank=True, to='driver.driver', verbose_name='راننده ها')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('saved_blogs', models.ManyToManyField(blank=True, to='blog.blog', verbose_name='بلاگ های ذخیره شده')),
                ('saved_products', models.ManyToManyField(blank=True, to='product.product', verbose_name='محصولات ذخیره شده')),
                ('saved_projects', models.ManyToManyField(blank=True, to='project.project', verbose_name='پروژه های ذخیره شده')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='LegalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='نام شرکت')),
                ('economic_code', models.SlugField(verbose_name='کد اقتصادی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('telephone', models.SlugField(verbose_name='تلفن ثابت')),
                ('postal_code', models.PositiveBigIntegerField(verbose_name='کد پستی')),
                ('national_id_company', models.PositiveBigIntegerField(verbose_name='کد ملی شرکت')),
                ('address', models.TextField(verbose_name='آدرس پستی')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='user/profile/image/', verbose_name='تصویر پروفایل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل حقوقی',
                'verbose_name_plural': 'پروفایل حقوقی کاربر',
            },
        ),
        migrations.CreateModel(
            name='RealProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='نام و نام خانوادگی')),
                ('national_id', models.PositiveBigIntegerField(verbose_name='کد ملی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('telephone', models.SlugField(verbose_name='تلفن ثابت')),
                ('postal_code', models.PositiveBigIntegerField(verbose_name='کد پستی')),
                ('type', models.CharField(choices=[('customer', 'خریدار'), ('seller', 'فروشنده')], default='customer', max_length=20, verbose_name='نوع کاربر')),
                ('address', models.TextField(verbose_name='آدرس پستی')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='user/profile/image/', verbose_name='تصویر پروفایل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='real_profile', to=settings.AUTH_USER_MODEL)),
                ('social_media', models.ManyToManyField(blank=True, to='user.socialmedia', verbose_name='شبکه اجتماعی')),
            ],
            options={
                'verbose_name': 'پروفایل حقیقی',
            },
        ),
        migrations.CreateModel(
            name='Marketer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='نام و نام خانوادگی')),
                ('image', models.ImageField(upload_to='marketing/marketer/profile/', verbose_name='عکس پروفایل')),
                ('active_phone', models.SlugField(max_length=11, unique=True, verbose_name='شماره تماس فعال')),
                ('social_phone', models.SlugField(max_length=11, unique=True, verbose_name='شماره شبکه اجتماعی')),
                ('time_work', models.CharField(choices=[('full-time', 'تمام وقت'), ('part-time', 'پاره وقت')], default='part-time', max_length=10, verbose_name='مدت زمان کار')),
                ('start_time_work', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع کار')),
                ('end_time_work', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان کار')),
                ('type', models.CharField(choices=[('phone', 'تلفنی'), ('internet', 'اینترنتی'), ('presence', 'حضوری')], default='phone', max_length=10, verbose_name='نوع بازاریاب')),
                ('national_id', models.PositiveBigIntegerField(verbose_name='کد ملی')),
                ('social_media', models.ManyToManyField(to='user.socialmedia', verbose_name='شبکه اجتماعی')),
            ],
            options={
                'verbose_name': 'بازاریاب',
                'verbose_name_plural': 'بازاریاب ها',
            },
        ),
    ]
