# Generated by Django 5.1.1 on 2024-10-27 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realprofile',
            name='social_media',
        ),
    ]
