# Generated by Django 5.1.1 on 2024-10-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalprofile',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='legalprofile',
            name='social_phone',
        ),
        migrations.AlterField(
            model_name='realprofile',
            name='social_media',
            field=models.ManyToManyField(blank=True, to='user.socialmedia', verbose_name='شبکه اجتماعی'),
        ),
    ]
