# Generated by Django 5.1.1 on 2024-09-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profuser', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drivers',
            field=models.ManyToManyField(blank=True, to='profuser.driver', verbose_name='راننده های کاربر'),
        ),
    ]
