# Generated by Django 5.1.1 on 2024-09-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalprofile',
            name='national_card',
        ),
        migrations.RemoveField(
            model_name='realprofile',
            name='national_card',
        ),
    ]
