# Generated by Django 5.1.1 on 2024-10-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('product', '0002_initial'),
        ('project', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_blogs',
            field=models.ManyToManyField(blank=True, to='blog.blog', verbose_name='بلاگ های ذخیره شده'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_products',
            field=models.ManyToManyField(blank=True, to='product.product', verbose_name='محصولات ذخیره شده'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_projects',
            field=models.ManyToManyField(blank=True, to='project.project', verbose_name='پروژه های ذخیره شده'),
        ),
    ]
