# Generated by Django 5.1.1 on 2024-09-13 11:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_code',
            field=models.SlugField(blank=True, max_length=5, null=True, verbose_name='کد تایید'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.SlugField(max_length=11, unique=True, verbose_name='موبایل'),
        ),
        migrations.CreateModel(
            name='LegalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('address', models.TextField(verbose_name='آدرس پستی')),
                ('postal_code', models.PositiveBigIntegerField(verbose_name='کد پستی')),
                ('telephone', models.SlugField(verbose_name='تلفن ثابت')),
                ('social_phone', models.SlugField(verbose_name='شماره موبایل شبکه اجتماعی')),
                ('national_code', models.PositiveBigIntegerField(verbose_name='کد ملی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('national_card', models.ImageField(upload_to='user/real-profile/national-card/', verbose_name='آپلود کارت ملی')),
                ('name', models.CharField(max_length=256, verbose_name='نام شرکت')),
                ('economic_code', models.SlugField(verbose_name='کد اقتصادی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل حقوقی',
            },
        ),
        migrations.CreateModel(
            name='RealProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('address', models.TextField(verbose_name='آدرس پستی')),
                ('postal_code', models.PositiveBigIntegerField(verbose_name='کد پستی')),
                ('telephone', models.SlugField(verbose_name='تلفن ثابت')),
                ('social_phone', models.SlugField(verbose_name='شماره موبایل شبکه اجتماعی')),
                ('national_code', models.PositiveBigIntegerField(verbose_name='کد ملی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('national_card', models.ImageField(upload_to='user/real-profile/national-card/', verbose_name='آپلود کارت ملی')),
                ('name', models.CharField(max_length=256, verbose_name='نام و نام خانوادگی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='real_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل حقیقی',
            },
        ),
    ]
