# Generated by Django 5.1.1 on 2024-10-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_saved_blogs_user_saved_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realprofile',
            name='type',
            field=models.CharField(choices=[('customer', 'خریدار'), ('seller', 'فروشنده'), ('seller-customer', 'خریدار-فروشنده')], default='customer', max_length=20, verbose_name='نوع کاربر'),
        ),
    ]
