# Generated by Django 5.1.1 on 2024-10-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_legalprofile_social_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realprofile',
            name='type',
            field=models.CharField(choices=[('customer', 'خریدار'), ('seller', 'فروشنده')], default='customer', max_length=20, verbose_name='نوع کاربر'),
        ),
    ]
