# Generated by Django 5.1.1 on 2024-10-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_realprofile_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name='ارسال sms'),
        ),
    ]
