# Generated by Django 5.1.1 on 2024-10-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_realprofile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realprofile',
            name='social_phone',
        ),
    ]
