# Generated by Django 5.1.1 on 2024-10-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_drivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dd',
            field=models.BooleanField(default=False),
        ),
    ]
