# Generated by Django 5.1.1 on 2024-10-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_realprofile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_panel_active',
            field=models.BooleanField(default=False, verbose_name='پنل فعال است'),
        ),
    ]
