# Generated by Django 5.1.1 on 2024-10-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_panel_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalprofile',
            name='company_registration_number',
        ),
        migrations.RemoveField(
            model_name='legalprofile',
            name='foundation_date',
        ),
        migrations.RemoveField(
            model_name='legalprofile',
            name='founder_company',
        ),
        migrations.RemoveField(
            model_name='legalprofile',
            name='national_id',
        ),
        migrations.AddField(
            model_name='legalprofile',
            name='national_id_company',
            field=models.PositiveBigIntegerField(default=None, verbose_name='کد ملی شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile/image/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AddField(
            model_name='realprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile/image/', verbose_name='تصویر پروفایل'),
        ),
    ]
