# Generated by Django 5.1.1 on 2024-10-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_dd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='drivers',
        ),
    ]
