# Generated by Django 5.1.1 on 2024-10-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_drivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dd',
        ),
    ]
