# Generated by Django 5.1.1 on 2024-10-16 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_legalprofile_company_registration_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketer',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='marketer',
            name='percent',
        ),
    ]
