# Generated by Django 5.1.1 on 2024-10-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_marketer_discount_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketer',
            name='authenticated_code',
        ),
    ]
