# Generated by Django 5.1.1 on 2024-10-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        ('user', '0006_remove_user_dd'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drivers',
            field=models.ManyToManyField(blank=True, to='driver.driver', verbose_name='راننده ها'),
        ),
    ]
