# Generated by Django 5.1.1 on 2024-11-08 12:26

import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('good', 'خوب'), ('middle', 'متوسط'), ('bad', 'بد')], default='middle', max_length=10, verbose_name='نوع بازخورد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'بازخورد',
                'verbose_name_plural': 'بازخورد تیکت',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان')),
                ('is_from_admin', models.BooleanField(default=False, verbose_name='از طرف ادمین است ')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('number', models.SlugField(blank=True, null=True, verbose_name='شماره تیکت')),
                ('status', models.CharField(choices=[('closed', 'بسته شده'), ('responsed', 'پاسخ داده شد'), ('pending-admin', 'در انتظار پاسخ ادمین'), ('pending', 'در انتظار بررسی'), ('responsed-user', 'پاسخ توسط مشتری')], default='pending', verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
        migrations.CreateModel(
            name='TicketDetailPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('info_ticket', models.TextField(verbose_name='توضیحات صفحه تیکت')),
            ],
            options={
                'verbose_name': 'صفحه جزییات تیکت',
                'verbose_name_plural': 'مدیرت صفحه جزییات تیکت',
            },
        ),
        migrations.CreateModel(
            name='TicketFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='ticket/files/', verbose_name='فایل')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل ها',
            },
        ),
        migrations.CreateModel(
            name='TicketPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان کادر')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن کادر')),
                ('feedback_popup_text', models.TextField(blank=True, null=True, verbose_name='متن پاپ اپ بازخورد تیکت')),
            ],
            options={
                'verbose_name': 'صفحه تیکت ها',
                'verbose_name_plural': 'صفحه تیکت ها',
            },
        ),
    ]
