# Generated by Django 5.1.1 on 2024-10-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_from_admin',
            field=models.BooleanField(default=False, verbose_name='از طرف ادمین است '),
        ),
    ]
