# Generated by Django 5.1.1 on 2024-10-27 08:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان کادر')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن کادر')),
            ],
            options={
                'verbose_name': 'صفحه تیکت ها',
                'verbose_name_plural': 'صفحه تیکت ها',
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('closed', 'بسته شده'), ('responsed', 'پاسخ داده شد'), ('pending-admin', 'در انتظار پاسخ ادمین'), ('pending', 'در انتظار بررسی'), ('responsed-user', 'پاسخ توسط مشتری')], default='pending', verbose_name='وضعیت'),
        ),
    ]
