# Generated by Django 5.1.1 on 2024-10-12 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticketfile_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('closed', 'بسته شده'), ('responsed', 'پاسخ داده شد'), ('pending-admin', 'در انتظار پاسخ ادمین'), ('checking', 'در انتظار بررسی'), ('pending-user', 'در انتظار پاسخ کاربر')], default='closed', verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
