# Generated by Django 5.1.1 on 2024-10-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='department',
        ),
    ]
