# Generated by Django 5.1.1 on 2024-11-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpage',
            name='feedback_popup_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن پاپ اپ بازخورد تیکت'),
        ),
    ]
