# Generated by Django 5.1.1 on 2024-11-07 11:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticketpage_feedback_popup_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketDetailPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('info_ticket', models.TextField(verbose_name='توضیحات صفحه تیکت')),
            ],
            options={
                'verbose_name': 'صفحه جزییات تیکت',
                'verbose_name_plural': 'مدیرت صفحه جزییات تیکت',
            },
        ),
    ]
