# Generated by Django 5.1.1 on 2024-10-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_status_alter_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='ticket/files/', verbose_name='فایل شماره ۱'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='file_2',
            field=models.FileField(blank=True, null=True, upload_to='ticket/files/', verbose_name='فایل شماره ۲'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='file_3',
            field=models.FileField(blank=True, null=True, upload_to='ticket/files/', verbose_name='فایل شماره ۳'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='file_4',
            field=models.FileField(blank=True, null=True, upload_to='ticket/files/', verbose_name='فایل شماره ۴'),
        ),
    ]
