# Generated by Django 5.1.1 on 2024-10-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_is_from_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('closed', 'بسته شده'), ('responsed', 'پاسخ داده شد'), ('pending-admin', 'در انتظار پاسخ ادمین'), ('pending', 'در انتظار بررسی'), ('pending-user', 'در انتظار پاسخ کاربر')], default='pending', verbose_name='وضعیت'),
        ),
    ]
