# Generated by Django 5.1.1 on 2024-10-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_ticket_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='number',
            field=models.SlugField(blank=True, null=True, verbose_name='شماره تیکت'),
        ),
    ]
