# Generated by Django 5.1.1 on 2024-10-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticketpage_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان'),
        ),
    ]
