# Generated by Django 5.1.1 on 2024-10-13 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_file_1_ticket_file_2_ticket_file_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='file_1',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='file_2',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='file_3',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='file_4',
        ),
        migrations.AddField(
            model_name='ticket',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='ticket.ticket'),
        ),
    ]
