# Generated by Django 5.1.1 on 2024-09-27 08:40

import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('is_send', models.BooleanField(default=False, verbose_name='ارسال شده')),
                ('is_valid', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('delivery_time', models.CharField(choices=[('12', '12 ساعت'), ('24', '24 ساعت'), ('72', '72 ساعت')], default='24', max_length=2, verbose_name='زمان تحویل کالا')),
                ('delivery_type', models.CharField(choices=[('driver', 'معرفی راننده'), ('send-factory', 'ارسال از درب کارخانه'), ('factory', 'تحویل درب کارخانه')], default='send-factory', max_length=20, verbose_name='نوع تحویل')),
                ('ident_code', models.SlugField(blank=True, max_length=5, null=True, verbose_name='کد معرف')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='نام و نام خانوادگی واریز کننده')),
                ('credit_card_number', models.SlugField(verbose_name='شماره حساب')),
                ('image', models.ImageField(upload_to='order/slip/', verbose_name='تصویر فیش واریزی')),
                ('iban', models.SlugField(verbose_name='شماره شبا')),
                ('time', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ واریز')),
            ],
            options={
                'verbose_name': 'فیش واریزی',
                'verbose_name_plural': 'فیش های واریزی',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(verbose_name='متن')),
            ],
            options={
                'verbose_name': 'قانون',
                'verbose_name_plural': 'قوانین و مقررات',
            },
        ),
    ]
