# Generated by Django 5.1.1 on 2024-09-19 14:43

import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('is_valid', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('delivery_time', models.CharField(choices=[('12', '12 ساعت'), ('24', '24 ساعت'), ('72', '72 ساعت')], default='24', max_length=2, verbose_name='زمان تحویل کالا')),
                ('delivery_type', models.CharField(choices=[('driver', 'معرفی راننده'), ('send-factory', 'ارسال از درب کارخانه'), ('factory', 'تحویل درب کارخانه')], default='send-factory', max_length=20, verbose_name='نوع تحویل')),
                ('ident_code', models.SlugField(blank=True, max_length=5, null=True, verbose_name='کد معرف')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
    ]
