# Generated by Django 5.1.1 on 2024-10-16 14:00

import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='order/pay-slip/files/', verbose_name='فایل فیش واریزی')),
                ('time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال فیش واریزی')),
            ],
            options={
                'verbose_name': 'فیش واریزی',
                'verbose_name_plural': 'فیش های واریزی',
            },
        ),
        migrations.CreateModel(
            name='PreInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('total_price', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='قیمت کل')),
                ('is_for_collegue', models.BooleanField(default=False, verbose_name='برای همکار است')),
                ('is_for_customer', models.BooleanField(default=False, verbose_name='برای مشتری است')),
                ('is_final', models.BooleanField(default=False, verbose_name='نهایی شده')),
            ],
            options={
                'verbose_name': 'پیش فاکتور',
                'verbose_name_plural': 'پیش فاکتور ها',
            },
        ),
        migrations.CreateModel(
            name='PreInvoiceProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('count', models.PositiveBigIntegerField(default=1, verbose_name='مقدار')),
                ('unit', models.CharField(default='کیلو گرم', max_length=256, verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(verbose_name='متن')),
            ],
            options={
                'verbose_name': 'قوانین و مقررات خرید کاربر',
                'verbose_name_plural': 'قوانین و مقررات خرید کاربر',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('state', models.CharField(blank=True, choices=[('accept', 'تایید شده'), ('reject', 'عدم تایید'), ('paid', 'پرداخت شده')], max_length=20, null=True, verbose_name='وضعیت سفارش')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('tracking_code', models.SlugField(blank=True, null=True, verbose_name='کد رهگیری')),
                ('delivery_time', models.CharField(choices=[('12', '12 ساعت'), ('24', '24 ساعت'), ('48', '48 ساعت'), ('72', '72 ساعت')], default='24', max_length=2, verbose_name='زمان تحویل کالا')),
                ('delivery_type', models.CharField(blank=True, choices=[('not-send', 'ارسال نشده (درحال پردازش)'), ('driver', 'تحویل راننده'), ('company', 'ارسال توسط شرکت')], max_length=20, null=True, verbose_name='نوع تحویل')),
                ('official_invoice', models.FileField(blank=True, null=True, upload_to='order/official-invoice/', verbose_name='فاکتور رسمی')),
                ('ident_code', models.SlugField(blank=True, max_length=5, null=True, verbose_name='کد معرف')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.driver', verbose_name='راننده')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
    ]
