# Generated by Django 5.1.1 on 2024-10-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products_count',
            field=models.ManyToManyField(blank=True, to='product.count', verbose_name='محصولات'),
        ),
    ]
