# Generated by Django 5.1.1 on 2024-10-31 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0001_initial'),
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_slips', to='order.order'),
        ),
        migrations.AddField(
            model_name='preinvoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_invoice', to='order.order'),
        ),
        migrations.AddField(
            model_name='preinvoiceproduct',
            name='pre_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.preinvoice'),
        ),
        migrations.AddField(
            model_name='preinvoiceproduct',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.productsystem', verbose_name='شرح کالا'),
        ),
        migrations.AddField(
            model_name='productcount',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_counts', to='order.order', verbose_name='سفارش'),
        ),
        migrations.AddField(
            model_name='productcount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول'),
        ),
    ]
