# Generated by Django 5.1.1 on 2024-10-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='order_tracking_number',
            field=models.IntegerField(null=True, verbose_name='شماره پیگیری سفارش'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='sheba_number',
            field=models.PositiveBigIntegerField(null=True, verbose_name='شماره کارت واریز کننده'),
        ),
    ]
