# Generated by Django 5.1.1 on 2024-11-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش ها'},
        ),
    ]
