# Generated by Django 5.1.1 on 2024-11-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcount',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
