# Generated by Django 5.1.1 on 2024-10-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ident_code',
        ),
    ]
