# Generated by Django 5.1.1 on 2024-10-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'قوانین و مقررات خرید کاربر', 'verbose_name_plural': 'قوانین و مقررات خرید کاربر'},
        ),
    ]
