# Generated by Django 5.1.1 on 2024-09-21 06:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(verbose_name='متن')),
            ],
            options={
                'verbose_name': 'قانون',
                'verbose_name_plural': 'قوانین و مقررات',
            },
        ),
    ]
