# Generated by Django 5.1.1 on 2024-10-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.SlugField(blank=True, null=True, verbose_name='کد رهگیری'),
        ),
    ]
