# Generated by Django 5.1.1 on 2024-10-13 12:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
        ('system', '0002_alter_productsystem_buy_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='official_invoice',
            field=models.FileField(blank=True, null=True, upload_to='order/official-invoice/', verbose_name='فاکتور رسمی'),
        ),
        migrations.CreateModel(
            name='PreInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('total_price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت نهایی')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_invoice', to='order.order')),
            ],
            options={
                'verbose_name': 'پیش فاکتور',
                'verbose_name_plural': 'پیش فاکتور ها',
            },
        ),
        migrations.CreateModel(
            name='PreInvoiceProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('count', models.PositiveBigIntegerField(default=1, verbose_name='مقدار')),
                ('unit', models.CharField(default='کیلو گرم', max_length=256, verbose_name='واحد')),
                ('is_for_collegue', models.BooleanField(default=False, verbose_name='برای همکار است')),
                ('is_for_customer', models.BooleanField(default=False, verbose_name='برای مشتری است')),
                ('pre_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.preinvoice')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.productsystem', verbose_name='شرح کالا')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
