# Generated by Django 5.1.1 on 2024-10-29 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_listshoppage_orderpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrderPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='عنوان')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
            ],
            options={
                'verbose_name': 'سوابق خرید',
                'verbose_name_plural': 'صفحه سوابق خرید',
            },
        ),
    ]
