# Generated by Django 5.1.1 on 2024-10-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinvoice',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='نهایی شده'),
        ),
    ]
