# Generated by Django 5.1.1 on 2024-11-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinvoice',
            name='code',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='شماره پیش فاکتور'),
        ),
    ]
