# Generated by Django 5.1.1 on 2024-11-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_preinvoice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinvoiceproduct',
            name='unit',
            field=models.CharField(default='کیلو گرم', max_length=128, verbose_name='واحد'),
        ),
    ]
