# Generated by Django 5.1.1 on 2024-10-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_preinvoice_is_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinvoiceproduct',
            name='total_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
