# Generated by Django 5.1.1 on 2024-10-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_ident_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('factory', 'ارسال از درب کارخانه توسط شرکت'), ('customer', 'تحویل کالا درب کارخانه توسط مشتری'), ('driver', 'معرفی راننده باربر توسط مشتری')], max_length=20, null=True, verbose_name='نوع تحویل'),
        ),
    ]
