# Generated by Django 5.1.1 on 2024-09-21 06:57

import django.db.models.deletion
import django_jalali.db.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, verbose_name='نام و نام خانوادگی واریز کننده')),
                ('credit_card_number', models.SlugField(verbose_name='شماره حساب')),
                ('iban', models.SlugField(verbose_name='شماره شبا')),
                ('time', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ واریز')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_slips', to='order.order')),
            ],
            options={
                'verbose_name': 'فیش واریزی',
                'verbose_name_plural': 'فیش های واریزی',
            },
        ),
    ]
