# Generated by Django 5.1.1 on 2024-10-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_official_invoice_preinvoice_preinvoiceproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preinvoice',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='preinvoiceproduct',
            name='is_for_customer',
            field=models.BooleanField(default=True, verbose_name='برای مشتری است'),
        ),
    ]
