# Generated by Django 5.1.1 on 2024-10-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_delivery_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products_count',
        ),
    ]
