# Generated by Django 5.1.1 on 2024-10-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_preinvoice_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinvoice',
            name='total_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='قیمت نهایی'),
        ),
    ]
