# Generated by Django 5.1.1 on 2024-10-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='products_count',
        ),
    ]
