# Generated by Django 5.1.1 on 2024-10-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_preinvoiceproduct_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinvoiceproduct',
            name='total_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مجموع'),
        ),
    ]
