# Generated by Django 5.1.1 on 2024-11-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_preinvoiceproduct_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preinvoice',
            name='code',
        ),
    ]
