# Generated by Django 5.1.1 on 2024-09-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='image',
            field=models.ImageField(default=None, upload_to='order/slip/', verbose_name='تصویر فیش واریزی'),
            preserve_default=False,
        ),
    ]
