# Generated by Django 5.1.1 on 2024-09-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_payslip_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='is_send',
            field=models.BooleanField(default=False, verbose_name='ارسال شده'),
        ),
    ]
