# Generated by Django 5.1.1 on 2024-10-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_preinvoice_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preinvoiceproduct',
            name='is_for_collegue',
        ),
        migrations.RemoveField(
            model_name='preinvoiceproduct',
            name='is_for_customer',
        ),
        migrations.AddField(
            model_name='preinvoice',
            name='is_for_collegue',
            field=models.BooleanField(default=False, verbose_name='برای همکار است'),
        ),
        migrations.AddField(
            model_name='preinvoice',
            name='is_for_customer',
            field=models.BooleanField(default=True, verbose_name='برای مشتری است'),
        ),
    ]
