# Generated by Django 5.1.1 on 2024-10-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_preinvoiceproduct_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='credit_card_number',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='iban',
        ),
    ]
