# Generated by Django 5.1.1 on 2024-10-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_payslip_credit_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='sheba_number',
        ),
    ]
