# Generated by Django 5.1.1 on 2024-10-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_preinvoiceproduct_is_for_collegue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinvoice',
            name='is_for_customer',
            field=models.BooleanField(default=False, verbose_name='برای مشتری است'),
        ),
    ]
