# Generated by Django 5.1.1 on 2024-10-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_productcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcount',
            options={'verbose_name': 'مقدار محصول', 'verbose_name_plural': 'مقادیر محصول'},
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, choices=[('accept', 'تایید شده'), ('reject', 'عدم تایید'), ('paid', 'پرداخت شده'), ('pending', 'در انتظار تایید')], max_length=20, null=True, verbose_name='وضعیت سفارش'),
        ),
    ]
