# Generated by Django 5.1.1 on 2024-10-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_payslip_sheba_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinvoiceproduct',
            name='buy_price',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت برای فروش'),
        ),
        migrations.AddField(
            model_name='preinvoiceproduct',
            name='colleague_price',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت برای همکار'),
        ),
    ]
