# Generated by Django 5.1.1 on 2024-10-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_productcount_options_alter_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('accept', 'تایید شده'), ('reject', 'عدم تایید'), ('paid', 'پرداخت شده'), ('pending', 'در انتظار تایید')], default='pending', max_length=20, verbose_name='وضعیت سفارش'),
        ),
    ]
