# Generated by Django 5.1.1 on 2024-10-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_preinvoiceproduct_buy_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preinvoiceproduct',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='preinvoiceproduct',
            name='colleague_price',
        ),
    ]
