# Generated by Django 5.1.1 on 2024-10-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcount',
            name='value',
            field=models.PositiveIntegerField(default=1, verbose_name='مقدار محصول'),
        ),
    ]
