# Generated by Django 5.1.1 on 2024-10-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_productcount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinvoice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
