# Generated by Django 5.1.1 on 2024-10-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_preinvoiceproduct_buy_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preinvoice',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='preinvoiceproduct',
            name='total_price',
        ),
    ]
