# Generated by Django 5.1.1 on 2024-10-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_preinvoice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('factory', 'ارسال از درب کارخانه توسط شرکت'), ('customer', 'تحویل کالا درب کارخانه توسط مشتری'), ('driver', 'معرفی راننده باربر توسط مشتری'), ('pending', 'ارسال نشده در حال پردازش')], max_length=20, null=True, verbose_name='نوع تحویل'),
        ),
    ]
