# Generated by Django 5.1.1 on 2024-10-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_preinvoice_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinvoice',
            name='total_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت کل'),
        ),
    ]
