# Generated by Django 5.1.1 on 2024-10-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_preinvoice_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preinvoice',
            name='total_price',
        ),
    ]
