# Generated by Django 5.1.1 on 2024-10-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_preinvoice_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinvoice',
            name='total_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='قیمت کل'),
        ),
    ]
