# Generated by Django 5.1.1 on 2024-10-15 06:10

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_preinvoice_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='description',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='image',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='name',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='order_tracking_number',
        ),
        migrations.AddField(
            model_name='payslip',
            name='file',
            field=models.FileField(default=None, upload_to='order/pay-slip/files/', verbose_name='فایل فیش واریزی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payslip',
            name='time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال فیش واریزی'),
        ),
    ]
