# Generated by Django 5.1.1 on 2024-10-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_remove_payslip_description_remove_payslip_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_send',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, choices=[('accept', 'تایید شده'), ('reject', 'عدم تایید'), ('paid', 'پرداخت شده')], max_length=20, null=True, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('12', '12 ساعت'), ('24', '24 ساعت'), ('48', '48 ساعت'), ('72', '72 ساعت')], default='24', max_length=2, verbose_name='زمان تحویل کالا'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('not-send', 'ارسال نشده (درحال پردازش)'), ('driver', 'تحویل راننده'), ('company', 'ارسال توسط شرکت')], max_length=20, null=True, verbose_name='نوع تحویل'),
        ),
    ]
